record/assets/javascripts/app.js
record/index.html.in

Use annotation for hidden columns/tables and display column/table names.
Sort reference tables according to display names.

Chaise #111

---

Makefile
matrix/index.html.in
scripts/app.js
scripts/controller/ermrestMatrixController.js
scripts/matrix.js
styles/matrix.css
views/ermmatrix.html

This pull request adds the matrix page; but for now it's using random (static) data.

Matrix Viewer with Static Data

---

record/assets/javascripts/app.js
record/index.html.in

Test links
https://dev.misd.isi.edu/~jchen/chaise/record/#1/legacy:dataset/id=4833 (with url patterns)
https://dev.misd.isi.edu/~jchen/chaise/record/#1/legacy:dataset/id=263 (empty url pattern)

#179 Support URL pattern annotation on details page

---

viewer/viewer.css

Osd integration styles

---

test/e2e/chaise.page.js
test/e2e/record/00-search.result.column.spec.js
test/e2e/record/01-result.detail.page.spec.js

I will implement more tests when it is decided what to be tested next.
Sometimes error like this (https://saucelabs.com/beta/tests/f4e938face2f432998a744b0bf22c1f6/watch) occurred. It happened twice when I was using Chaise on my browser (Chrome) and met it several times when doing automation tests.

Skipped some tests and fixed bugs

---

scripts/tour.js
styles/tour.css
views/ermretrieveresults.html

This PR changes some tour descriptions. It also changes tutorial button into a link.

Site tour tweaks

---

Makefile
recordset/index.html.in
recordset/recordset.html
recordset/recordset.js

For more information and examples, see https://github.com/informatics-isi-edu/chaise/issues/264

Recordset prototype

---

recordset/recordset.js

I chose to sort them O(N Log N) rather than just do
one loop O(N) because we might also want to then
look at the shortest keys and find the one(s) that
are made of int or serial column(s). If it comes to
that, then we might also want to push this into the
ermrestjs API.

Pick the first key colset from the shortest (#343)

---

record/assets/javascripts/app.js

Record app was not handling login if session not found.

Fixed record app session handling #362

---

karma-test-config/sample-karma.conf.js
karma.conf.js
test/e2e/login/protractor.conf.js
test/e2e/record/00-search.result.column.spec.js
test/e2e/record/01-result.detail.page.spec.js
test/e2e/record/protractor.conf.js
test/e2e/search/protractor.conf.js
test/unit/util.spec.js

@svoinea 
Added Login handling for record page.
Fixed browser size issue in protractor configuration.
Changed `encodeURI` testcase to start using the [fixedEncodeURIComponent](https://github.com/informatics-isi-edu/chaise/blob/master/common/utils.js#L15) function of factory [UriUtils](https://github.com/informatics-isi-edu/chaise/blob/master/common/utils.js#L6) of angular module [chaise.utils](https://github.com/informatics-isi-edu/chaise/blob/master/common/utils.js#L4).

Change Encode URI utils unit test to consume the angular factory function and added Login handling for Record Page

---

record/assets/javascripts/app.js
recordset/recordset.js

This pull request address Chaise #484. Record and recordset apps were forcing login, regardless whether it is necessary or not. This update removes that and redirects to login page only when 401 unauthorized error is received.

Disable forcing login in record and recordset

---

common/navbar.js
common/templates/navbar.html

Looking at [chaise-config.js](https://github.com/informatics-isi-edu/chaise/blob/master/chaise-config-sample.js), there are three variables that are used for the navbar:
- `headTitle`
- `navbarBrand`
- `navbarBrandImage`
This PR adds these variables to the common navbar (issue: #492).
@robes @jrchudy @howdyjessie Can you please review this PR?

navbar: Use chaise config for brand image, brand text, and brand url

---

common/utils.js
record-two/record.app.js
recordedit/form.controller.js
recordedit/recordEdit.app.js
recordset/recordset.js
viewer/viewer.app.js

This update added to the common URL parsing to handle complex filter parameters.

Parse complex filters in URL (#465)

---

recordedit/form.controller.js

Support disjunctive filters in RecordEdit redirect #461

RecordEdit redirect to recordset with disjunctive filters #461

---

test/e2e/data_setup/schema/product.json

Made change in annotation in product schema https://github.com/informatics-isi-edu/ermrestjs/pull/173.

Fixed changes related to PR 163 in ermrestjs

---

record-two/index.html.in
record-two/record.controller.js
record-two/record.css
test/e2e/specs/record2/helpers.js

This PR addresses #553 by adding a "Permalink" link to Record 2, much like it was in the old record app.

Record2: Add permalink

---

Makefile
common/table.js
common/templates/table.html
common/utils.js
record-two/record.app.js
recordset/recordset.html
recordset/recordset.js
test/e2e/data_setup/config/recordset.dev.json
test/e2e/data_setup/schema/product.json
test/e2e/specs/recordset/data-dependent/00-recordset.presentation.spec.js
test/e2e/specs/recordset/data-dependent/protractor.conf.js
test/e2e/specs/recordset/helpers.js
test/e2e/utils/chaise.page.js

* Addresses issue #562: Display HTML in record table.
* Use compact context in recordset
* Initial e2e testing setup for Recordset.

Display HTML in Record Table

---

Makefile

This **PR** fixes the issue with timeouts regarding unavailability of chaiseConfig. Thus, we don't need to angularize chaiseConfig as mentioned in issue #576 . 
You can test it here https://dev.isrd.isi.edu/~chirag/chaise

Made chaise-config.js to be loaded before all javascript files in makefile for all Apps

---

recordedit/form.controller.js

This can be tested [here](https://dev.rebuildingakidney.org/~jchudy/chaise/recordedit/#2/Protocol:Protocol/Title=Generation%20of%20kidney%20organoids%20from%20human%20pluripotent%20stem%20cells&Version=1.0).
This resolves issure #583.

markdown appears as long text in recordedit

---

common/table.js
common/templates/table.html
record/record.controller.js
recordset/recordset.html
recordset/recordset.js

PR for issue #611 
Move row linking method to the record-table directive. So that apps don't need to implement its own row linking method.

Common row linking method for record-table directive #611

---

common/utils.js
record/record.app.js
recordset/recordset.js
test/e2e/specs/record/data-dependent/01-record.editbutton.spec.js
test/e2e/specs/record/data-dependent/02-record.createbutton.spec.js

This **PR** fixes issue #626. It adds a factory method which is supposed to be called by the record app when it is run. This factory method adds a live event handler on the dropdown button open action. It determines whether there is enough space for it to open below or top and renders it accordingly.

Dynamic dropdown button rendering 

---

Makefile
common/alerts.js
common/errors.js
common/templates/alerts.html
record/index.html.in
record/record.app.js
recordset/recordset.html
recordset/recordset.js

PR for #340
The main issue with #340 is address by this ermrestjs pull request 
https://github.com/informatics-isi-edu/ermrestjs/pull/214
The changes in Chaise just handles and displays the exceptions from ermrestjs.
* Added a missing error callback handler for resolve.
* Created a alerts directive for showing error messages.
* Record and Recordset use alerts directive to display error message

Better Error Handling of Incomplete Fragment ID

---

common/styles/app.css
common/templates/table.html
test/e2e/specs/recordset/helpers.js
test/e2e/utils/chaise.page.js

PR for #473 (only need to implement tooltip)

Record Table Column Tooltip

---

common/utils.js

Fixed a few missing encoding for schema and table names.

Encoding for uri components

---

scripts/tour.js

You can check it out [here](https://dev.isrd.isi.edu/~ashafaei/chaise/search).

Fix placement of tour popover when sidebar is on the left

---

recordedit/form.controller.js
recordedit/index.html.in
test/e2e/specs/recordedit/helpers.js
test/e2e/utils/chaise.page.js

This PR addresses #664.
Assigning to @jrchudy and tagging @hongsudt to look at the text, an example of which can be seen [here](https://dev.gpcrconsortium.org/~jessie/chaise/recordedit/#1/experiments:purification_sop) at the "Procedure" column.

Add help text below Markdown inputs

---

record/index.html.in
record/record.controller.js
record/record.css
test/e2e/specs/record/helpers.js
test/e2e/utils/chaise.page.js

This PR adds a button/link to show all related tables (i.e. show empty tables too).
Assigning to @shinyichen.

Show All Related Entities button

---

common/table.js
common/templates/recordset.html
common/templates/table.html
record/index.html.in
record/record.app.js
recordset/recordset.html
recordset/recordset.js

Addresses #656 and #657 to have a wrapper directive around current RecordTable directive. The new directive has a set of controls for the table; search, paging, page limit.

Recordset Directive

---

recordedit/recordEdit.app.js

Gets the session from the promise returned by the Session factory
instead of the root scope.

This should address race condition found in #703

---

Makefile

Added checksums to common files in makefile

---

common/templates/searchPopup.modal.html
recordedit/form.controller.js
recordedit/index.html.in
test/e2e/specs/recordedit/data-independent/add/00-recordedit.add.spec.js
test/e2e/specs/recordedit/data-independent/edit/01-recordedit.edit.spec.js
test/e2e/specs/recordedit/helpers.js
test/e2e/utils/chaise.page.js

This PR includes tests for opening the foreign key modal and selecting a row. There are also tests for removing the value from the input field as well as opening the modal and closing it (then verifying no value was set upon doing so).

Foreignkey tests

---

test/e2e/specs/record/helpers.js
test/e2e/specs/recordedit/data-independent/edit/02-recordedit.delete.spec.js
test/e2e/specs/recordset/helpers.js

The row click function tests are working properly.

row click test not failing now

---

recordedit/index.html.in
recordedit/recordEdit.css

This PR fixes the issue https://github.com/informatics-isi-edu/chaise/issues/760 Pseudocolumns wrap badly.
The change can be tested here https://dev.gpcrconsortium.org/~chirag/chaise/recordedit/#1/experiments:sop

Columns wrap edit

---

common/ellipses.js
common/styles/app.css
test/e2e/data_setup/config/recordset.dev.json
test/e2e/utils/protractor.configuration.js

This PR fixes the test-case for column content wrapping failing locally.

Col wrap testfix

---

recordedit/form.controller.js
recordedit/index.html.in
recordedit/recordEdit.css

This **PR** fixes issue #772.
You can test it here.
https://dev.gpcrconsortium.org/~chirag/chaise/recordedit/#1/experiments:experiment

Freezed the column names and the plus button so they are not scrollable

---

common/styles/app.css
common/templates/recordset.html

Add a tooltip next to the search. #813

Search tooltips #774.

---

common/ellipses.js
common/styles/app.css
common/templates/ellipses.html

This PR fixes issues #819 and #820. 
https://synapse-dev.isrd.isi.edu/~chirag/chaise/recordset/#1/Zebrafish:Behavior@sort(Image%20Date::desc::)

More less changes

---

common/styles/app.css

Fixed issue #827

---

common/templates/ellipses.html

Fixed issue #855

---

common/templates/recordset.html
recordedit/index.html.in
test/e2e/specs/recordedit/helpers.js

* Auto focus search box #786
* Move 'items per page' next to search box
* Add tooltip for the 'Add' button
* Remove add button from recordedit #837

Auto focus search box in recordset #768 and other minor UI adjustments

---

recordedit/recordEdit.css

This PR fixes the issue #868  with modal loader getting misaligned on bigger resolutions.
Can be tested here https://dev.isrd.isi.edu/~chirag/chaise/recordedit/#1/legacy:dataset

Modal loader misaligned

---

common/modal.js
common/templates/table.html
recordset/recordset.js

This PR fixes issue #889. It also addresses a problem with sorting when the icons are hidden.
This can be tested [here](https://dev.isrd.isi.edu/~jchudy/chaise/recordset/#1/legacy:dataset).

Sort icons show properly

---

common/ellipses.js
common/modal.js
common/table.js
common/templates/recordset.html
common/templates/searchPopup.modal.html
recordset/recordset.html
recordset/recordset.js

This PR implements the search feature as described in issue #791 
The search directive has 2 variables viz. backgroundSearch & foregroundSearch to track which search is going on currently.
Changes can be seen [here](https://dev.isrd.isi.edu/~chirag/chaise/recordedit/#1/legacy:dataset)
The recordset app needs to change a bit, because it updates the whole page while you're typing text in search input box. I have added a switch to enable/disable the auto search.
The delay is 200ms for now.

Search popup

---

common/templates/recordset.html
test/e2e/specs/recordset/add/01-recordset.add.spec.js
test/e2e/specs/recordset/data-dependent/00-recordset.presentation.spec.js
test/e2e/specs/recordset/helpers.js
test/e2e/utils/chaise.page.js

This PR converts sleep to wait in recordset tests as discussed in issue #853 .

Recordset tests

---

Makefile
common/table.js
common/templates/recordset.html

@shinyichen  Made changes as requested for search in recordset mentioned [here]( https://github.com/informatics-isi-edu/chaise/pull/894#issuecomment-269041407)
Can be tested [here](https://dev.isrd.isi.edu/~chirag/chaise/recordedit/#1/legacy:dataset?invalidate=recordset-504121301244567)

Search changes in recordset

---

test/e2e/specs/record/copy-btn/06-record.copybutton.spec.js
test/e2e/specs/record/data-dependent/00-record.presentation.spec.js
test/e2e/specs/record/data-dependent/01-record.editbutton.spec.js
test/e2e/specs/record/data-dependent/02-record.createbutton.spec.js
test/e2e/specs/record/data-dependent/04-record.deletebutton.spec.js
test/e2e/specs/record/helpers.js
test/e2e/specs/record/no-delete-btn/05-record.no-delete-btn.spec.js
test/e2e/specs/record/related-table/03-record.related-table-link.spec.js

This partially addresses #853 by converting `browser.sleep` to `browser.wait` in Record app tests.

Convert sleeps to waits in record tests

---

test/e2e/specs/record/copy-btn/06-record.copybutton.spec.js
test/e2e/specs/record/data-dependent/00-record.presentation.spec.js
test/e2e/specs/record/data-dependent/01-record.editbutton.spec.js
test/e2e/specs/record/data-dependent/02-record.createbutton.spec.js
test/e2e/specs/record/data-dependent/04-record.deletebutton.spec.js
test/e2e/specs/record/helpers.js
test/e2e/specs/record/no-delete-btn/05-record.no-delete-btn.spec.js
test/e2e/specs/record/related-table/03-record.related-table-link.spec.js

The record tests were failing on  my machine due to the use of waitForUrl instead of waitForElement when waiting fort he page to load. Converted all of them.

Converted waitForUrl to waitForElement in record tests

---

recordedit/index.html.in
test/e2e/specs/recordedit/data-dependent/composite-key/04-recordedit.composite-key.spec.js
test/e2e/specs/recordedit/data-dependent/submission-disabled/05-recordedit.button-disabled.spec.js
test/e2e/specs/recordedit/data-independent/add-defaults/07-recordedit.defaults.spec.js
test/e2e/specs/recordedit/data-independent/add/00-recordedit.add.spec.js
test/e2e/specs/recordedit/data-independent/delete-record/03-recordedit.delete-button.spec.js
test/e2e/specs/recordedit/data-independent/edit/01-recordedit.edit.spec.js
test/e2e/specs/recordedit/data-independent/edit/02-recordedit.delete.spec.js
test/e2e/specs/recordedit/helpers.js

This PR includes changes to the recordedit specs to change all sleeps (except really short ones) to waits.
There is also a change to `recordedit.index.html` because there was a minor spelling mistake.

Recordedit sleeps to waits

---

recordedit/form.controller.js

Move the code to proper place so that cookie is always set.

Setting cookie was placed at the wrong place. #911

---

common/ellipses.js
common/modal.js
common/table.js
common/templates/ellipses.html
common/templates/recordset.html
common/templates/table.html
record/index.html.in
record/record.app.js
record/record.controller.js
recordedit/form.controller.js
recordset/recordset.js
test/e2e/data_setup/config/related-table-link.dev.json
test/e2e/specs/record/helpers.js
test/e2e/specs/record/related-table/07-record.related-table-actions.spec.js
test/e2e/specs/recordedit/data-dependent/composite-key/04-recordedit.composite-key.spec.js
test/e2e/specs/recordedit/helpers.js
test/e2e/specs/recordset/add/01-recordset.add.spec.js
test/e2e/specs/recordset/helpers.js
test/e2e/utils/chaise.page.js

PR for #838. Create an action column. 
* In recordset, column should have view|edit|delete actions. 
* In record, table have view|edit|delete or unlink.
* Update the table after delete or edit made.
* In recordedit modal, column should only have select action.
* Remove row click action from table.

Action Colum

---

test/e2e/data_setup/schema/product-no-serial.json
test/e2e/data_setup/schema/product-record.json
test/e2e/data_setup/schema/product-unordered-related-tables.json
test/e2e/data_setup/schema/product.json
test/e2e/specs/recordedit/data-independent/add/00-recordedit.add.spec.js

[Changes in this PR in ermrestjs](https://github.com/informatics-isi-edu/ermrestjs/pull/318), will broke the test cases in chaise. This PR will fix the test cases.

Fix Test Cases For Columns Heuristics

---

common/templates/recordset.html
common/templates/table.html
test/e2e/specs/record/helpers.js
test/e2e/specs/recordset/helpers.js
test/e2e/utils/chaise.page.js

This PR addresses issue #987. When a table doesn't have any results to display, it will still show the table heading with 1 result row that states, "No Results Found".

No results row in tables

---

scripts/ermrest.js

The "cid=search" query parameter is added through the url_cid(url) function.

Added "cid=search" to the search queries of the ermrest requests.

---

recordedit/index.html.in

This PR reduces the padding between the add and actual form in recordedit.
https://dev.isrd.isi.edu/~chirag/chaise/recordedit/#19067/product:accommodation.
This is how it looked before
https://dev.isrd.isi.edu/chaise/recordedit/#19067/product:accommodation
Let me know if the url is not accessible. I cannot work on the default catalog as I don't have privileges to edit anything.

Just a UI fix to recordedit for reducing top margin

---

Makefile
common/table.js
common/templates/recordset.html
test/e2e/data_setup/config/recordset.dev.json
test/e2e/data_setup/schema/product.json
test/e2e/specs/recordset/data-dependent/00-recordset.presentation.spec.js
test/e2e/utils/chaise.page.js

This PR adds an e2e test for issue #999. This PR has to be merged *after* [this one](https://github.com/informatics-isi-edu/ermrestjs/pull/369) in `ermrestJS`.

Test for Paging

---

Makefile
common/errorDialog.controller.js
common/errors.js
common/table.js
common/templates/errorDialog.modal.html
recordset/recordset.js

Opening this pull request with my comments for `recordset`.

Recordset Errors

---

Makefile
common/alerts.js
common/authen.js
common/bindHtmlUnsafe.js
common/delete-link.js
common/ellipses.js
common/errorDialog.controller.js
common/errors.js
common/filters.js
common/modal.js
common/navbar.js
common/table.js
common/utils.js
common/validators.js
record/record.app.js
record/record.controller.js
recordedit/form.controller.js
recordedit/recordEdit.app.js
test/e2e/specs/record/data-dependent/00-record.presentation.spec.js
test/e2e/specs/record/helpers.js
viewer/annotations/annotations.controller.js
viewer/annotations/annotations.service.js
viewer/annotations/comments.service.js
viewer/image-metadata/metadata.controller.js
viewer/test/alerts.service.spec.js

This PR addresses the Record app and common folder portions of #1012.

Error handling in Record app and common folder

---

common/errors.js
common/templates/errorDialog.modal.html

This PR fixes issue with incomplete error message for Firefox. It also disables window.onError for search app.
@hongsudt Please confirm its working.

Fixes issue related to Incomplete error message on Firefox and disables window.onerror in Search App

---

recordedit/form.controller.js

contextualize the reference before calling .create

---

record/index.html.in
test/e2e/specs/multi-permissions/visibility/00-record.spec.js
test/e2e/specs/record/helpers.js

This PR addresses issue #1045.

Change Link to Add

---

common/utils.js
recordset/recordset.js
test/e2e/specs/recordset/data-dependent/00-recordset.presentation.spec.js
test/e2e/specs/recordset/data-dependent/chaise-config.js

This PR addresses issue #756. This was already implemented but was not behaving properly because of some corner cases. This PR fixes the known issues and adds tests to verify the functionality is working properly.

Chaise config defaults

---

record/index.html.in
recordedit/index.html.in
viewer/index.html.in

Apps specify utf-8 charset

---

scripts/ermrest.js

Updated the code to support search on facets NULL values.

Support search on facets NULL values

---

test/e2e/specs/navbar/base-config/chaise-config.js
test/e2e/specs/navbar/no-logo-no-brandtext/chaise-config.js
test/e2e/specs/record/copy-btn/chaise-config.js
test/e2e/specs/record/data-dependent/chaise-config.js
test/e2e/specs/record/no-delete-btn/05-record.no-delete-btn.spec.js
test/e2e/specs/record/no-delete-btn/chaise-config.js
test/e2e/specs/recordedit/data-independent/add/chaise-config.js
test/e2e/specs/recordedit/data-independent/delete-record/chaise-config.js
test/e2e/specs/recordedit/data-independent/edit/chaise-config.js
test/e2e/specs/recordset/data-dependent/chaise-config.js
test/e2e/specs/viewer/data-dependent/chaise-config.js

Updated chaise config files for e2e tests so they only represent the necessary configuration options for the tests that that config pertains to. This is the first change towards parallelizing the e2e tests.

Chaise Configs for E2E Tests

---

recordedit/form.controller.js

Fixed issue #1106

---

.gitignore
common/upload.js
recordedit/form.controller.js
test/e2e/data_setup/config/recordadd.dev.json
test/e2e/specs/recordedit/data-independent/add/00-recordedit.add.spec.js
test/e2e/specs/recordedit/helpers.js

This PR fixes issue https://github.com/informatics-isi-edu/ermrestjs/issues/408 as well as adding concrete support for aborting uploads.
The code can be tested here 
https://dev.gpcrconsortium.org/~chirag/chaise/recordedit/#1/assets:target_files

Fixed abort issue with upload

---

common/upload.js
record/record.controller.js

I added some logging for the $scope.$apply errors. I will update this on monday with logging to a log folder on each deployment so we can later track how often this occurs and better establish a mechanism to handling it.

added some logging for $scope.$apply

---

common/table.js
record/record.controller.js
recordedit/form.controller.js

This PR addresses issue #1136.
Made a change to check for the `invalidate` query param before making a function call with a value that is `undefined`.

Window updated

---

recordedit/recordEdit.app.js
test/e2e/data_setup/schema/recordedit/defaults.json
test/e2e/specs/default-config/recordedit/add-defaults.spec.js

This PR addresses issue #1147, which I created based on the changes I made to the defaults logic yesterday.

Adjusted logic for populating the UI in create mode

---

record/index.html.in
record/record.app.js
test/e2e/specs/all-features-confirmation/record/presentation.spec.js
test/e2e/specs/default-config/record/related-table-link.spec.js
test/e2e/utils/record-helpers.js

Changes to show detailed information about the number records in the table
1st Case: (When all the results are displayed)
"Showing first 15 results" to "showing first 15 results" (sentence case was somehow looking more prominent so we decided to have all verbose in small case)
2nd Case: (When no results are displayed)
"no results" to "no results found" so that this is consistent with what was shown in the empty table body

issue#980 - Changes to show detailed information about the number records in the table

---

chaise-config-sample.js
common/styles/app.css

Footer styling bug fix

---

record/record.controller.js

Related Issue: #1193
Test cases should be in another PR.

Fix canCreateRelated function in record controller

---

common/footer.js
common/styles/app.css

Footer misplacement fix

---

common/authen.js

Using angular `$window` service rather than javascript global variable and function name changed to get the deployment path name

Using angular service rather than js global variable

---

common/utils.js
recordedit/form.controller.js

This PR adds functionality to the `recordedit` app to check for a column's base type if we don't know how to create an input for it's type if it's a user defined domain type.
This is for issue #1234.

Recordedit input basetype

---

test/e2e/data_setup/data/product/association_table.json
test/e2e/data_setup/data/product/related_table.json
test/e2e/data_setup/schema/record/product-unordered-related-tables-actions.json
test/e2e/data_setup/schema/record/product-unordered-related-tables-links.json
test/e2e/specs/all-features-confirmation/record/presentation.spec.js
test/e2e/specs/all-features/record/related-table-link.spec.js

This PR adds test cases for association entities. 
**Add**: Will let you add a relationship between the base and related table.
**Edit**: Will let you edit a relationship between the base and the related table.
**View**: Will land you the record page of the related entity (Leaf table) of the association.
**View** More: Will land you to the recordset page of the association table rather than leaf table.

Test cases for association entities

---

recordset/recordset.html

Change the tooltip for download CSV button.

Change the tooltip for download CSV button

---

common/table.js
common/templates/recordset.html

I refactored the multi-edit code to use the tuple object rather than the display object I created. Both @RFSH and I need these changes for the faceting components we are making and @amitjha21 needs it for the multi-select changes he's making on the record app.

Multi-edit uses tuple for selected rows

---

.travis.yml
Makefile
git_version_info.sh

Travisinstall

---

common/templates/record.html
record/index.html.in
record/record.app.js
record/record.controller.js

This PR addresses #1244 .
Can be tested here:
https://dev.rebuildingakidney.org/~amit/chaise/record/#2/Protocol:Protocol/ID=22

Refresh issue in inbound FK tables after adding new records

---

Makefile

This PR fixes issue https://github.com/informatics-isi-edu/chaise/issues/1189 by changing the rules for e2e testing.

Removed redundant test command for protractor and merged them into a common function

---

common/modal.js
common/navbar.js
common/styles/app.css
common/templates/navbar.html
common/templates/profile.modal.html
test/e2e/specs/all-features/navbar/base-config.spec.js

- A dropdown is added to the profile name that's displayed on the navbar.
- Upon clicking the profile name, a profile card appears with all the other information found in 
webauthn's client object.
- The card has all the group names, the user is a part of, which is clickable and will navigate to 
globus group detail page when clicked.

Profile card for chaise

---

common/utils.js
recordedit/recordEdit.app.js
test/e2e/specs/all-features/recordedit/permissions-visibility.spec.js
test/e2e/utils/chaise.page.js

This PR adds check to make sure user is logged in on recordedit page as mentioned in issue https://github.com/informatics-isi-edu/chaise/issues/1339. Anonymous users aren't allowed to create/update entities.
https://dev.isrd.isi.edu/~chirag/chaise/recordedit/#1/isa:dataset

Force anonymous user to login on recordedit page 

---

common/errors.js
common/templates/errorDialog.modal.html
common/utils.js
record/record.app.js
recordedit/recordEdit.app.js

Addresses issue #1200 
Custom error function changed in `Errors` factory.
No changes required for `ERMrestjs`.

Refactor error 1200

---

common/errors.js
common/utils.js
test/e2e/specs/all-features-confirmation/record/presentation.spec.js
test/e2e/specs/all-features-confirmation/recordset/presentation.spec.js

Fixes `ermrestjs` dependency issue in `common\utils.js`

Error issue search fix

---

common/errors.js
common/modal.js
common/templates/errorDialog.modal.html
common/utils.js
package.json
record/record.app.js
test/e2e/specs/all-features-confirmation/record/presentation.spec.js

This PR addressee issue #1352.
Can be tested [here](https://dev.isrd.isi.edu/~amit/chaise/record/#1/isa:dataset/id=26923345454).
Test cases are added in `test/e2e/specs/all-features-confirmation/record/presentation.spec.js`

Record not found error should be meaningful 

---

common/recordCreate.js
recordedit/form.controller.js

This PR fixes the issue Asset Url Validation missing https://github.com/informatics-isi-edu/chaise/issues/1368.
https://dev.isrd.isi.edu/~chirag/chaise/recordedit/#36736/upload:file

Added the removed file upload url validation code

---

common/recordCreate.js
common/upload.js

This PR fixes this issue https://dev.isrd.isi.edu/~chirag/chaise/recordedit/#36736/upload:file related to file upload when choosing no file and pressing cancel.
https://dev.isrd.isi.edu/~chirag/chaise/recordedit/#36736/upload:file

Fixed issue with upload when cancelling file select

---

common/errors.js
common/table.js
common/templates/table.html
record/record.app.js
recordset/recordset.html
recordset/recordset.js
test/e2e/specs/delete-prohibited/recordset/ind-facet.spec.js

This PR addresses issue #1287.
Each app can be used with either a filter in the url or the facet blob in the url. Added back the Edit link on `recordset`.

Apps understand url with Faceting

---

common/faceting.js
common/modal.js
common/table.js
common/templates/ellipses.html

To differentiate between empty string and null value. It is only used by scalar faceting for now.

Add showNull to Recordset Directive Config

---

common/styles/app.css
record/record.css
recordedit/recordEdit.css

Added a div with css after the main container

---

test/e2e/data_setup/data/product/booking.json
test/e2e/data_setup/schema/record/product.json
test/e2e/specs/all-features-confirmation/record/presentation.spec.js
test/e2e/utils/record-helpers.js

Pure and binary#1409

---

common/ellipses.js
common/errors.js
common/faceting.js
common/modal.js
common/recordCreate.js
common/table.js
common/templates/table.html
common/utils.js
record/index.html.in
record/record.app.js
record/record.controller.js
recordedit/form.controller.js
recordedit/recordEdit.app.js
recordset/recordset.js

This PR includes:
1. Passing appropriate objects to be logged for each of the requests
made by chaise.
2. Adding logError method to log the terminal errors in ermrest.
To check the logs:
1. SSH to `dev.isrd` machine.
2. Switch user to root `su -`. 
3. Run `grep "dcctx" /var/log/messages`. You should see your last call entry in the log with name `dcctx`. Or you can `tail -f /var/log/messages | grep "action"` and then generate requests in chaise to check the actions that are being sent.
**NOTE** The foreignkey test cases are failing for me locally because it's not showing the total count. I tried with the master branch locally and it had the same problem.
Requires [ermrsetjs#589](https://github.com/informatics-isi-edu/ermrestjs/pull/589)
Related Issue: #1389

Pass Log Objects

---

common/templates/upload.html
common/upload.js
recordedit/form.controller.js
recordedit/index.html.in
test/e2e/data_setup/data/multi-column-types/table_w_generated_columns.json
test/e2e/data_setup/schema/recordedit/multi-column-types.json
test/e2e/specs/default-config/recordedit/multi-col-types.spec.js

I'm not sure if the test case that I added was enough. Please let me know if I need to add extra test cases

Make Sure Disabled File Upload Works Properly

---

common/authen.js
common/ellipses.js
common/errors.js
common/faceting.js
common/recordCreate.js
common/table.js
record/record.app.js
record/record.controller.js
recordedit/recordEdit.app.js
recordset/recordset.js

This PR addresses issue #1446.

refactored promise structures in chaise

---

common/modal.js
common/utils.js

Undelete `facetRelatedErrorStatus` in `utils.js`.

Error deleted entries

---

.gitignore
common/errors.js
common/modal.js
common/templates/errorDialog.modal.html
common/utils.js
recordedit/recordEdit.app.js
test/e2e/specs/all-features-confirmation/errors/errors.spec.js

This PR addresses #1448 .
Error modal has been changed for 404 errors with login link appearing for anonymous users.
In case of errors, history will be maintained for back button in the bowsers.
Test case for history is in [`errors.spec.js`](https://github.com/informatics-isi-edu/chaise/compare/errorModal404?expand=1#diff-98cb82d265253c464440d33edaa85663)

Error modal404

---

common/modal.js
common/templates/errorDialog.modal.html
common/utils.js

opened for tests to run in travis.

Unauthorized login message was too direct

---

common/alerts.js
common/faceting.js
common/resizable.js
common/styles/app.css
common/table.js
common/templates/faceting/collapse-btn.html
common/templates/faceting/faceting.html
common/templates/recordsetWithFaceting.html
common/utils.js
record/index.html.in
record/record.controller.js
record/record.css
test/e2e/specs/all-features-confirmation/record/presentation.spec.js
test/e2e/utils/chaise.page.js

This PR addresses issue #1487.

Facet collapse btn redesign

---

common/faceting.js
common/modal.js
common/templates/searchPopup.modal.html
record/index.html.in
recordedit/index.html.in
recordedit/recordEdit.app.js
recordset/recordset.html
recordset/recordset.js
test/e2e/specs/all-features-confirmation/record/presentation.spec.js
test/e2e/specs/all-features-confirmation/recordedit/add.spec.js
test/e2e/specs/all-features-confirmation/recordedit/edit.spec.js
test/e2e/specs/all-features-confirmation/recordset/presentation.spec.js
test/e2e/specs/default-config/recordedit/multi-edit.spec.js
test/e2e/utils/chaise.page.js
test/e2e/utils/record-helpers.js
test/e2e/utils/recordedit-helpers.js

This PR will add tooltip to the table names that we are showing in the headers.
Issue: #1484

Add Tooltip to Headers

---

common/modal.js
common/utils.js

add login message for 404 errors

---

common/faceting.js
test/e2e/specs/delete-prohibited/recordset/ind-facet.spec.js

Changes for exclusive range facets. The chaise build will fail, after merging the [ermrestjs PR](https://github.com/informatics-isi-edu/ermrestjs/pull/651) we should run the build in this PR.

Exclusive Range

---

common/templates/upload.html
common/upload.js
common/validators.js
recordedit/form.controller.js
recordedit/index.html.in
test/e2e/data_setup/schema/recordedit/product-add.json
test/e2e/specs/all-features-confirmation/recordedit/add.spec.js
test/e2e/utils/chaise.page.js
test/e2e/utils/recordedit-helpers.js

This PR adds validation to `recordedit` to verify if the user selected files to upload that are valid based on model annotations.

Filename ext filter support

---

common/table.js
common/templates/table.html
record/index.html.in
recordedit/index.html.in

Opening this PR to make sure test cases still pass. Will update body tomorrow morning.
Related wiki page:
https://github.com/informatics-isi-edu/chaise/wiki/Custom-CSS-Styling-tips
@RFSH  what should we do about the function that hashes the pseudocolumn names? Should that be exposed like we discussed the other day so whomever can take a path and know what the output hash will be?

Schema table column classes

---

common/errors.js

**errors.js**
Added the phrase "Try clearing your cache" to the message on the terminal error modal.

Add text to terminal error#1508

---

common/alerts.js
common/templates/alerts.html
common/utils.js

Following changes have been made to add login link in Session Alert : 
**alerts.js**
1. Added a new compile directive which uses the internal angular service $compiler to bind the scope with the element.
2. Added controller to fire the method : Session.loginInAPopUp();
**alerts.html**
3. Changed the tag "ng-bind-html" to "compile". This is done so that the "ng-click" on the Log in link gets registered.
4. Added the corresponding "ng-controller" div. 
**utils.js**
3. Added anchor <a> tag so the text "Log in" is now a clickable link.

Added Login Link in Session Alert #1530

---

common/footer.js
common/styles/app.css
common/templates/footer.html

@hongsudt asked me ab out the grey bar showing up for the footer while the page loads and stated that even when the footer is not defined, it shows the grey bar before it disappears. 
- refactored the footer directive to longer delay when to show/hide the directive. 
- ng-show on internal <div> for the footer based on rendered markdown
- CSS changes so background color applies to the internal container of the footer

Footer directive refactor

---

common/alerts.js
common/ellipses.js
common/faceting.js
common/modal.js
common/styles/app.css
common/table.js
common/templates/ellipses.html
common/templates/recordset.html
common/templates/recordsetSelectFaceting.html
common/templates/searchPopup.modal.html
common/templates/table.html
common/utils.js
test/e2e/data_setup/data/faceting/main.json
test/e2e/specs/delete-prohibited/recordset/misc-facet.spec.js

This PR will improve the way we're showing URL limitation alert. We used to show the alert after users clicks on submit (in facet modal). But now, we're checking the url on each change on the selected rows.
Issues: #1519 #1216

Improve URL Limitation Handling In Recordset

---

common/utils.js
record/index.html.in
record/record.controller.js
recordset/index.html.in
recordset/recordset.controller.js
test/e2e/specs/all-features-confirmation/recordset/presentation.spec.js
test/e2e/utils/chaise.page.js

- Added the Permalink and DownloadCSV tooltips to the messageMap constant in util.js
- Added test cases to check the tooltips in recordset/presentation.spec.js

Consistent tooltips

---

common/recordCreate.js
common/templates/upload.html
common/upload.js
common/utils.js
common/validators.js
test/e2e/specs/all-features-confirmation/recordedit/add.spec.js

filetype validation was triggering during edit mode. Moved this validation to the bind event for when the file input changes instead of the text input.
Made a change in `recordCreate` where an error without a message (I saw it as an error with code 0) would throw a terminal error.

moved Filetype validation

---

Makefile
common/ellipses.js
common/record.js
common/templates/recordAction.html
common/templates/searchPopup.modal.html
common/utils.js
record/index.html.in
record/record.controller.js
recordedit/form.controller.js
test/e2e/specs/all-features-confirmation/recordset/presentation.spec.js
test/e2e/specs/all-features/record/related-table.spec.js
test/e2e/utils/chaise.page.js
test/e2e/utils/record-helpers.js

Inverse changes to revert changes for batch unlink because it caused a regression for unlink of single entities.

revert branch "batch-unlink"

---

record/record.css

- Made the record-side-pan as hidden while printing
- Adjusted the width of the table columns for printing
- Adjusted the page margins

 Fixed white space issues while printing record page

---

common/table.js
common/templates/table.html
common/utils.js
recordset/recordset.app.js
test/e2e/specs/all-features-confirmation/recordset/presentation.spec.js
test/e2e/specs/all-features/recordset/permissions-visibility.spec.js

- Added a tooltip to the view header in recordset table based on whether the header is View or Action
- Added the tooltip text to the recordset model

View header tooltip

---

common/alerts.js
common/authen.js
common/delete-link.js
common/ellipses.js
common/errors.js
common/export.js
common/faceting.js
common/footer.js
common/inputs.js
common/login.js
common/navbar.js
common/record.js
common/recordCreate.js
common/table.js
common/upload.js
common/utils.js
docs/user-docs/chaise-config.md
recordedit/form.controller.js
viewer/annotations/annotations.controller.js
viewer/annotations/comments.controller.js

- Added a function in chaise.utils to find the chaise path (UriUtils.chaiseDeploymentPath())
- Converted template URLs of all directives from relative to absolute
- Used the above function in logInHelper in authen.js and removed getDeploymentPathName()

Made all template urls absolute

---

common/templates/record.html
record/index.html.in

It's a very small change and the whole point of this PR is just to make sure test cases are passing in travis

don't show content if accordion is closed

---

chaise-config-sample.js
common/navbar.js
common/templates/navbar.html
common/templates/navbarMenu.html

issues and redundency in navbar

---

Makefile

This is just to fix the behavior that is described in #1637. We need to find the actual issue, and change the version back to latest.

change jQuery version of new apps to 1

---

common/modal.js
common/styles/app.css
common/templates/shareCitation.modal.html
record/record.app.js
record/record.controller.js
test/e2e/specs/all-features-confirmation/record/presentation.spec.js
test/e2e/specs/all-features/record/copy-btn.spec.js
test/e2e/utils/chaise.page.js
test/e2e/utils/record-helpers.js

This PR adds support to download the citation (if present) in the `BibTex` format.
Fixed the citation annotation to be more inline with what is defined in the [citation issue](https://github.com/informatics-isi-edu/ermrestjs/issues/678) and shown [here on RBK](https://dev.rebuildingakidney.org/about/usage.html).
Other changes include:
- collating config setup for record app
- refactoring some of the share dialog tests to be simpler
- prepending `chaise-` so the share dialog can more accurately be identified

Download bibtex

---

.travis.yml
common/faceting.js
common/modal.js
common/table.js
common/templates/recordsetSelectFaceting.html
test/e2e/data_setup/schema/recordset/faceting.json
test/e2e/specs/delete-prohibited/recordset/ind-facet.spec.js
test/e2e/specs/delete-prohibited/recordset/misc-facet.spec.js
test/e2e/utils/chaise.page.js

1. Hide them based on the two newly added ermrestjs APIs.
2. Show null on top of the other options.
3. Show null option in the modal beside the not-null
I just need to add one extra test case for testing the "null" option in the modal.
#1640

Null facet

---

test/e2e/data_setup/data/product/accommodation.json

add property to an entity that shouldn't rely on the default value

---

common/faceting.js
common/templates/recordsetSelectFaceting.html
test/e2e/specs/delete-prohibited/recordset/ind-facet.spec.js
test/e2e/specs/delete-prohibited/recordset/misc-facet.spec.js

This PR will,
- disable the null check functionality from faceting.
- Fix a bug related to check presence facets.
issues: #1653 #1655

Remove null from recordset select with faceting

---

.travis.yml
common/faceting.js
common/templates/recordset.html
test/e2e/specs/delete-prohibited/recordset/misc-facet.spec.js
test/e2e/utils/chaise.page.js

This will add required functionalities for the custom facet feature. For more information please refer to [the corresponding ermrestjs PR](https://github.com/informatics-isi-edu/ermrestjs/pull/727).
The test case that I added won't run on travis. I don't think we need this test case in travis, but if you think that's necessary I can just remove the check for travis.
Issue: #1650

Custom facet

---

common/styles/app.css
record/index.html.in
record/record.controller.js

Added loading spinner and loading text to record app table of contents panel.

Loading text/spinner in ToC

---

common/modal.js
common/table.js
common/templates/errorDialog.modal.html

Added reload button for when a No Connection Error occurs during the loading of the application.

Reload button for No Connection Error

---

.travis.yml
test/e2e/data_setup/schema/recordset/faceting.json
test/e2e/specs/delete-prohibited/recordset/ind-facet.spec.js
test/e2e/specs/delete-prohibited/recordset/misc-facet.spec.js

This PR is going to fix the test cases that will break because of [ermrestjs#750](https://github.com/informatics-isi-edu/ermrestjs/pull/750) changes

 Don't show null and not-null for scalar not-null columns

---

common/navbar.js
common/templates/navbar.html
lib/navbar/navbar-app.md
lib/navbar/navbar.app.js
lib/navbar/sample-navbar.html

Very similar to the login app that was previously created. Added a call to set up the chaise config as well for the angular application. I probably should do the same for the login app although it doesn't rely on the chaise config.

navbar standalone app

---

chaise-config-sample.js
common/navbar.js
common/styles/appheader.css
common/templates/navbar.html
common/templates/navbarMenu.html
test/e2e/specs/all-features-confirmation/chaise-config.js
test/e2e/specs/all-features-confirmation/navbar/no-logo.spec.js

This PR changes the behavior of the navbar dropdown menus and sub menus. Before you could hover over the dropdown menus and they would open automatically. This PR removes that functionality so that sub menus will only open on click.

Navbar submenus open on click

---

common/styles/app.css
common/utils.js
record/index.html.in
record/record.controller.js
recordedit/form.controller.js
recordedit/index.html.in
recordset/index.html.in
recordset/recordset.controller.js

Added the version text that appears in the title of `recordset` app and in the subtitle for `record` and `recordedit`. Whether this applies to `recordedit` or not can be discussed based on how we want to handle a versioned `create` and `edit` page.

version # text

---

common/templates/upload.html
common/upload.js
recordedit/recordEdit.app.js

Made a change so that we are storing the uri value when submitting uploaded files but we show the filename in the UI. This was always the case before in create mode, but now it applies to edit as well.

added a tooltip to the file upload fields.

---

common/styles/app.css

Doesn't need a PR, but this I figured I would open one so we can discuss the change before it's merged.

removed style so text isn't shifted outside of it's div

---

common/ellipses.js
common/table.js
common/templates/recordset.html
common/templates/table.html
test/e2e/utils/record-helpers.js
test/e2e/utils/recordedit-helpers.js

Made small changes to the text of the buttons and their tooltips. Made some minor modifications for some test cases that would fail sometimes when run locally.

Select all on page

---

docs/dev-docs/e2e-test.md

The permission of the public html folder and how to upload the folder to the remote server.

[skip CI] Updating the e2e test document

---

.travis.yml
test/e2e/specs/default-config/recordedit/immutable-inputs.spec.js
test/e2e/specs/default-config/recordedit/multi-col-types.spec.js

This PR will fix the test cases that are broken because of [the recent ermrestjs change to assets](https://github.com/informatics-isi-edu/ermrestjs/pull/801).

update asset test cases

---

common/styles/scss/_buttons.scss
common/styles/scss/_recordset.scss
common/templates/delete-link/delete-btn.html
common/templates/delete-link/delete-link.html
common/templates/ellipsis.html
docs/style-guide/style-guide.html
viewer/index.html.in

Changes include:
- Increase the font size of action buttons
- Change color of action buttons
- Reduce the spacing in the action buttons cell
- Change the trash can icon.
Related issue: #1869
I'm still not sure if what I have it good enough. At first, I set the font-size to `1.25rem` and they looked good. But we wanted to also remove the padding. But by doing so the first cell became way too crowded so I had to reduce it and increase the padding a bit. It might need more adjustment. 
About changing the alignment of sort icon, to do so I had to reduce the font-size. I had to use a very small font-size to make the alignment the same way as we want, and at that point, the icon wasn't very visible so I decided not to make the change at all.

UI changes related to action buttons

---

recordedit/form.controller.js

Made sure the check in RE is done only if that tuple exists for the row index passed before clearing a value in the tuple.

Fix for copy bug

---

common/record.js
common/styles/scss/_record-app.scss
record/index.html.in
test/e2e/utils/record-helpers.js

- Modified the Explore button tooltip
- added tooltip to each table of contents option
- reduced the opacity of the ToC headings for tables with 0 rows

Record tooltip improvements

---

common/export.js
common/utils.js
docs/user-docs/custom-css.md
test/e2e/specs/all-features-confirmation/recordset/presentation.spec.js
test/e2e/specs/all-features/record/copy-btn.spec.js
test/e2e/specs/default-config/record/links.spec.js
test/e2e/utils/chaise.page.js
test/e2e/utils/record-helpers.js

Rewrote `makeSafeIdAttr` function to properly make class names and id attributes safe so that selectors will continue to work.
Ran the tests after and it all seems to be passing after messing around with the regular expression for far too long.

changed default CSV option

---

common/ellipsis.js
test/e2e/specs/all-features-confirmation/chaise-config.js
test/e2e/specs/all-features-confirmation/recordset/presentation.spec.js
test/e2e/specs/default-config/recordset/add.spec.js

This PR addresses the issue #1937.

run init function regardless of maxRecordsetRowHeight value

---

common/templates/searchPopup.modal.html
recordedit/index.html.in
test/e2e/specs/delete-prohibited/recordset/misc-facet.spec.js
test/e2e/utils/record-helpers.js
test/e2e/utils/recordedit-helpers.js

Changed text for submit button in recordedit app and in the pure and binary add popup. The facet multi select popup was not modified. Test cases added for the 3 places mentioned to verify the text is correct.
The foreign key single select popup does not have a submit button, so no change there either.

Change submit to save

---

common/styles/scss/_markdown-container.scss
common/styles/scss/_record-app.scss
common/templates/record.html

This PR adds the `chaise-autofill` class to the stylesheets.

Responsive iframe class

---

common/styles/scss/_navbar.scss
common/templates/navbar.html
docs/user-docs/navbar-app.md

Issue - https://github.com/informatics-isi-edu/chaise/issues/2025
**Before -** 
Clicking on Menu expands nothing
**After -**
Navbar visible
**Test link -** 
https://dev.rebuildingakidney.org/~kpherwan/chaise/recordset/#2/Microarray:Series@sort(RID)
https://dev.facebase.org/chaise/recordset/#1/isa:dataset@sort(release_date::desc::,RID)

2025 - Menu button now expands to show vertical navbar

---

common/utils.js
docs/user-docs/chaise-config.md

Please check issue description here - https://github.com/informatics-isi-edu/chaise/issues/2086
To test hit the okay button and check behavior.
Before - 
https://dev.facebase.org/chaise/record/#1/isa:dataset/
After - 
https://dev.facebase.org/~kpherwan/chaise/record/#1/isa:dataset/

2086 - change in URL to continue after logout

---

common/navbar.js
common/styles/scss/_navbar.scss
common/templates/errorDialog.modal.html

Related to https://github.com/informatics-isi-edu/chaise/issues/2071
Available to test on https://dev.rebuildingakidney.org/~kpherwan/chaise/recordset/#2/Protocol:Protocol@sort(RMT::desc::,RID)

2071 submenu goes offscreen

---

common/utils.js
record/record.app.js

Changes to support prompting the user to login when redirected from chaise by a static page.

prompt login query parameter

---

.github/workflows/e2e.yml
common/errors.js
common/record.js
record/record.app.js
record/record.controller.js
record/record.utils.js
test/e2e/data_setup/data/product/new_media_7.json
test/e2e/data_setup/data/product/new_media_8.json
test/e2e/data_setup/data/product/new_media_9.json
test/e2e/data_setup/schema/record/product-max-RT.json
test/e2e/data_setup/schema/record/product-unordered-related-tables-links.json
test/e2e/data_setup/schema/record/product.json
test/e2e/data_setup/schema/recordset/product-recordset.json
test/e2e/specs/all-features-confirmation/errors/errors.spec.js
test/e2e/specs/all-features/chaise-config.js
test/e2e/specs/all-features/record/copy-btn.spec.js
test/e2e/specs/all-features/record/related-table.spec.js

This PR will add changes related to [ermrestjs#685](https://github.com/informatics-isi-edu/ermrestjs/issues/685) which are:
- Show terminal error message for 409 errors (instead of raw ermrest message)
- Add test cases related to the filter in source changes in [ermrestjs#928](https://github.com/informatics-isi-edu/ermrestjs/pull/928)

Filter in source (phase 2)

---

.github/workflows/e2e.yml
test/e2e/data_setup/data/faceting/f1.json
test/e2e/data_setup/data/faceting/f1_outbound1.json
test/e2e/data_setup/schema/recordset/faceting.json
test/e2e/specs/delete-prohibited/recordset/ind-facet.spec.js
test/e2e/specs/delete-prohibited/recordset/misc-facet.spec.js
test/e2e/utils/recordset-helpers.js

This Pr will add test cases to faceting spec to ensure the changes in [ermrestjs#924](https://github.com/informatics-isi-edu/ermrestjs/pull/924) are working properly.

Add test cases for testing facets with subset path prefix

---

.github/workflows/e2e.yml
test/e2e/specs/default-config/recordset/add.spec.js

Over the past week I ran the failing "go back to recordset should refresh the table with the new record" multiple times and was finally able to fix it.
At first I added a click on title before testing to make sure it focuses, but as [you can see here](https://github.com/informatics-isi-edu/chaise/actions/runs/1890332629/attempts/12) it failed 40% of the time. Then I changed it two just switch without closing and [it still failed](https://github.com/informatics-isi-edu/chaise/actions/runs/1930723961).
While debugging this in Saucelabs, I realized that if I manually switch tab it actually works properly, so I decided to do this extra switch as part of the testing and as [you can see it passed 100% of the time](https://github.com/informatics-isi-edu/chaise/runs/5458263767?check_suite_focus=tr …

Fix borken test case 

---

.github/workflows/e2e.yml
test/e2e/data_setup/schema/recordedit/product-add.json
test/e2e/data_setup/schema/recordedit/product-edit.json
test/e2e/specs/all-features-confirmation/recordedit/add.spec.js
test/e2e/specs/all-features-confirmation/recordedit/edit.spec.js

As the title suggests, this PR will modify existing test cases to also test [this change in ermrestjs](https://github.com/informatics-isi-edu/ermrestjs/pull/956).

Add test cases for url_pattern changes in ermrestjs

---

test/e2e/utils/recordedit-helpers.js

Move modal title setter and add a 100 ms sleep before trying to open the modal again

Broken fk picker test in edit mode

---

docs/dev-docs/dev-guide.md
src/components/facet-choice-picker.tsx
src/components/faceting.tsx
src/components/recordset-table.tsx
src/components/recordset.tsx
src/components/search-input.tsx
src/components/table-header.tsx
test/e2e/specs/all-features-confirmation/recordset/presentation.spec.js
test/e2e/specs/default-config/recordset/add.spec.js
test/e2e/specs/default-config/recordset/edit.spec.js
test/e2e/specs/delete-prohibited/recordset/ind-facet.spec.js
test/e2e/utils/chaise.page.js

Open PR before merging to review my own code

React recordset tests

---

src/assets/scss/_faceting.scss
src/assets/scss/_input-switch.scss
src/assets/scss/_range-input.scss
src/assets/scss/app.scss
src/components/facet-range-picker.tsx
src/components/input-switch.tsx
src/components/range-inputs.tsx
src/components/recordset.tsx
src/utils/window-ref.ts

An input component used for inputing the start and end values for a range. 
This component will be used in the facet-range picker component.
Types supported: 
- int
- float
- numeric
- date
- timestamp
Validations:
- from < to
- int type can only input valid integers based on the following regex - /^\-?\d+$/
- float type can only input valid floats based on the following regex - /^\-?(\d+)?((\.)?\d+)?$/
- numeric type can only input valid floats based on the following regex - /^\-?(\d+)?((\.)?\d+)?$/
- date type should be a valid date (asserted by momentJS)
- datetime-local should be a valid datetime object (asserted by momentJS)
In case any validation fails the one the corresponding error messages are displayed:
- Please enter both From and To values
- From value cannot be greater than …

input-switch

---

src/components/login-dropdown.tsx
src/components/navbar.tsx
test/e2e/specs/all-features/navbar/base-config.spec.js
test/e2e/specs/all-features/navbar/protractor.conf.js

This PR has changes related to navbar e2e testing.
Changes:
The spec file test/e2e/specs/all-features/navbar/base-config.spec.js should be passing based on our current implementation of navbar in react.

Migrate navbar/base-config.spec.js

---

common/utils.js
docs/user-docs/chaise-config.md
src/services/config.ts
src/utils/constants.ts
test/e2e/data_setup/schema/recordset/active-list.json
test/e2e/specs/all-features-confirmation/chaise-config.js

This PR includes the chaise changes related to [ermrestjs#967](https://github.com/informatics-isi-edu/ermrestjs/pull/967).

Add templating object to chaise-config

---

package-lock.json
package.json
src/assets/scss/_input-switch.scss
src/assets/scss/_inputs.scss
src/components/clear-input-btn.tsx
src/components/input-switch.tsx
src/components/input-switch/color-field.tsx
src/components/inputs/color-field.tsx
src/hooks/click-outside.ts

As title suggests, this will add support for `rgb_hex_color` type.

Add color input

---

recordedit/form.controller.js
test/e2e/data_setup/data/multi-edit/f1.json
test/e2e/data_setup/data/multi-edit/multi-edit-table.json
test/e2e/data_setup/schema/recordedit/multi-edit.json
test/e2e/specs/default-config/recordedit/multi-edit.spec.js
test/e2e/utils/chaise.page.js

Running in github actions before merging into master and making similar changes to the `angularJS` branch.

Set all clear fk

---

Makefile
recordedit/form.controller.js
test/e2e/utils/protractor.configuration.js

This pull request fixes a bug found in the angularJS version of recordedit app.
Another change included allows the e2e tests to be run in headless mode in angularJS branch.

Angularjs bug fix

---

.github/workflows/e2e.yml
Makefile
docs/dev-docs/e2e-test.md
docs/dev-docs/test-faq.md
package-lock.json
package.json
test/e2e/specs/all-features-confirmation/recordedit/add.spec.js
test/e2e/utils/protractor.import.js
test/e2e/utils/protractor.parameterize.js

This PR will,
- Use the npm published version of ermrest-data-utils (https://github.com/informatics-isi-edu/ErmrestDataUtils/pull/21).
- Replace `request-q` with `axios`.

Clean up some dependencies

---

src/assets/scss/_input-switch.scss
src/components/input-switch/array-field.tsx
src/components/input-switch/json-field.tsx
src/components/input-switch/longtext-field.tsx
src/utils/input-utils.ts

This PR is related to 
https://github.com/informatics-isi-edu/chaise/issues/2318
It focuses on adding a padding when there is a scrollbar in the textarea which avoids overlapping between the text, cross button and scrollbar

Longtext input has x on top of scrollbar

---

src/components/modals/upload-progress-modal.tsx

Fixed bug with upload not properly queueing multiple files for upload causing the server to not be able to handle the incoming number of requests when uploading multiple files (5+). Fixed a bug where after aborting, file upload would still complete and submit the recordedit page.
The changes I made for these bugs:
- changed `erred` and `aborted` from `useState` to `useRef` since they are only ever used inside of other functions which are callbacks from promises.
- when functions are callbacks inside of promises, the react "state" is not updated for those functions since they get defined in the calling tree once the first function is called
- using a "ref" is meant to not trigger rerenders and therefore is mutable/accessible during long function calls in promise callbacks
- Changed `++` to …

File upload causing server to hang

---

src/assets/scss/_navbar.scss

Inconsistent styles that were found in staging.atlas-d2k.org when doing regression testing. The 3 issues in this PR include:
- consistent height for navbar in chaise apps and deriva webapps
- hover color for menu options when mousing over them
- active color when a navbar menu is open

Navbar css bugs

---

docs/dev-docs/dev-guide.md
src/components/input-switch/input-field.tsx
src/components/recordedit/form-row.tsx
src/components/recordedit/recordedit.tsx
src/components/recordset/table-row.tsx
src/providers/recordedit.tsx

Add a spinner over recordedit page when more forms are added (1 at a time or many). More details about the specifics of the implementation are in the comments in the code.

Clone spinner

---

.github/workflows/e2e.yml
test/e2e/specs/all-features-confirmation/record/presentation.spec.js
test/e2e/specs/all-features-confirmation/recordset/presentation.spec.js
test/e2e/specs/default-config/recordedit/immutable-inputs.spec.js
test/e2e/specs/default-config/recordedit/multi-col-types.spec.js
test/e2e/utils/record-helpers.js

This PR will update chaise test cases to work with changes in https://github.com/informatics-isi-edu/ermrestjs/pull/1002.

JSON null changes

---

docs/dev-docs/dev-guide.md
src/components/modals/iframe-field-modal.tsx
src/components/navbar/navbar.tsx
src/components/record/record.tsx
src/components/recordedit/multi-form-input-row.tsx
src/components/recordset/recordset.tsx
src/components/viewer/viewer-annotation-stroke-slider.tsx
src/components/viewer/viewer-menu-buttons.tsx
src/pages/login.tsx
src/providers/authn.tsx
src/providers/recordedit.tsx
src/services/config.ts
src/utils/constants.ts
src/utils/menu-utils.ts
src/utils/ui-utils.ts

This PR is for running test cases to make sure changing to `windowRef` doesn't break anything.

change cases where window is used to windowRef

---

src/components/navbar/navbar-dropdown.tsx
src/components/navbar/navbar.tsx

2363 navbar submenu stays open

---

test/e2e/specs/all-features-confirmation/record/presentation.spec.js
test/e2e/specs/all-features-confirmation/recordedit/add.spec.js
test/e2e/specs/all-features-confirmation/recordedit/edit.spec.js
test/e2e/utils/record-helpers.js
test/e2e/utils/recordedit-helpers.js

This will allow us to run chaise e2e test cases without installing ermrestjs.

Remove usage of mustache in test cases

---

package-lock.json
package.json

Reverts informatics-isi-edu/chaise#2440

Revert "Bump the eslint group with 3 updates"

---

src/components/modals/recordset-modal.tsx
src/components/record/related-table-actions.tsx
test/e2e/locators/modal.ts
test/e2e/locators/recordedit.ts
test/e2e/setup/playwright.configuration.ts
test/e2e/setup/playwright.model.ts
test/e2e/specs/all-features/playwright.config.ts
test/e2e/specs/all-features/record/related-table.spec.ts
test/e2e/specs/default-config/multi-form-input/multi-form-input-clone.spec.ts
test/e2e/specs/default-config/multi-form-input/multi-form-input-create.spec.ts
test/e2e/specs/default-config/multi-form-input/multi-form-input-edit.spec.ts
test/e2e/utils/recordedit-utils.ts

This PR was mainly created to improve the test cases. This includes,
- Adding proper wait for the "upload progress modal".
- Increasing timeout in clone and other test cases that rely on upload given that the page might take more than the default 5seconds to load.
- Running `allfeatures` spec test cases sequentially given that a lot of different test cases change catalog annotation or ACLs.
I also made the following improvements to record page:
- Change title of link/unlink pure and binary to use the same name displayed on the record page instead of table name (#1924).
- Change the label of the dismiss button for the "unlink pure and binary popup" to "Close" (#2257).

Improve test cases + small pure and binary modal improvement

---

src/assets/scss/_dropdown.scss
src/providers/viewer.tsx
src/utils/constants.ts
src/utils/head-injector.ts
src/utils/string-utils.ts
src/utils/window-ref.ts

Add chaise-safari class to the html body element. Add styles to fix a navbar menu bug with scrollbars showing.

Safari class + navbar bug fix

---

Makefile
src/components/record/record-main-section.tsx

Added `makeSafeIdAttr` to a place that it was missing. Opening this to run tests just in case but they did pass locally.

add mafeSafeIdAttr to id

---

Makefile
docs/user-docs/chaise-config.md
src/components/input-switch/json-field.tsx
src/components/input-switch/longtext-field.tsx
src/components/input-switch/text-field.tsx
src/utils/constants.ts
src/utils/input-utils.ts
test/e2e/data_setup/config/parallel-configs/all-features.dev.json
test/e2e/data_setup/config/recordedit/ascii-text-validation.config.json
test/e2e/data_setup/config/recordedit/ascii-text-validation.dev.json
test/e2e/data_setup/schema/recordedit/ascii-text-validation.json
test/e2e/specs/all-features-confirmation/recordedit/add.spec.ts
test/e2e/specs/all-features/chaise-config.js
test/e2e/specs/all-features/recordedit/ascii-text-validation.config.ts
test/e2e/specs/all-features/recordedit/ascii-text-validation.spec.ts
test/e2e/utils/recordedit-utils.ts
webpack/app.config.js

This PR applies the changes described in https://github.com/informatics-isi-edu/chaise/issues/2607.

Block non-ascii text values in recordedit

---

package-lock.json
package.json

Resolves https://github.com/informatics-isi-edu/chaise/security/dependabot/39

bump version of babel

---

.github/workflows/e2e.yml
Makefile
package-lock.json
package.json
src/components/modals/upload-progress-modal.tsx
src/models/record.ts
src/providers/record.tsx
src/services/config.ts
src/utils/record-utils.ts
webpack/app.config.js
webpack/templates/dynamic-load.js

This PR is to ensure the changes in https://github.com/informatics-isi-edu/ermrestjs/pull/1022 are working properly.
I'll update this description once all test cases are passing on CI.

Fix issues discovered by ermrestjs vite branch

---

.github/workflows/e2e.yml
src/components/faceting/facet-choice-picker.tsx
test/e2e/data_setup/data/faceting/main.json
test/e2e/data_setup/schema/recordset/faceting.json
test/e2e/specs/delete-prohibited/recordset/individual-facet.spec.ts
test/e2e/specs/delete-prohibited/recordset/misc-facet.spec.ts

This PR alongside https://github.com/informatics-isi-edu/ermrestjs/pull/1025 will ensure we're properly handling exact match for facets. Please refer to the ermrestjs PR for more information.
For chaise, I just had to make sure we're not blindly using `tuple.data` for JSON columns and calling `JSON.stringify` properly. I also added test cases to ensure everything is working as expected.

Fix issues in the json facet support

---

src/assets/scss/_recordedit.scss
src/components/recordedit/form-container.tsx
src/utils/ui-utils.ts

Fix the top horizontal scrollbar in recordedit

---

.github/workflows/e2e.yml
src/components/record/record.tsx
src/utils/record-utils.ts
test/e2e/data_setup/schema/record/product-unordered-related-tables-links.json
test/e2e/data_setup/schema/recordset/faceting.json
test/e2e/specs/all-features/record/related-table.spec.ts
test/e2e/specs/delete-prohibited/recordset/reorder-facet.spec.ts

This PR adds test cases to test the changes in https://github.com/informatics-isi-edu/ermrestjs/pull/1044.
I also made a minor change in how record page is setting the initial state of the page.

Test changes in ermrestjs#1044

---

.github/workflows/e2e.yml
src/components/modals/delete-confirmation-modal.tsx
test/e2e/specs/all-features-confirmation/record/delete-btn.spec.ts

Referer to https://github.com/informatics-isi-edu/ermrestjs/pull/1051 for more information.

Use proper RelatedReference class instead of generic Reference
