Makefile, test/e2e/record/protractor.conf.js, test/e2e/search/protractor.conf.js, test/e2e/search/search.spec.js
Change the Makefile, so that "make test" will exec 
```
"protractor conf_1.js && protractor conf_2.js && protractor conf_3.js"
```
instead of the previous
```
"protractor conf_1.js"
"protractor conf_2.js"
"protractor conf_3.js"
```
So protractor conf_2.js will be exec only if the previous tests all get passed. And any one failure will end the Travis build phase.
One drawback could be that potential test failures in later tests won't be seen, since they won't be exec if tests earlier fail. It's a work around for now.
=> Changes Makefile to make Travis to fail if any one test fails, and more test specs

viewer/app.js, viewer/index.html.in
This PR will:
- Allow users to create, edit, and delete annotations in Chaise instead of Annotorious
- Allow users to select and edit an anatomy term when creating or editing an annotation
=> Create, edit, delete annotations inside Chaise; add anatomy selection

record/assets/views/record.html
This is a quick fix for issue #325. Indicate (0) in the reference table header if table has no rows.
=> Empty table

common/interceptors.js, data-entry/form.controller.js, data-entry/index.html.in
This pull request fulfills #352. It adds a feature that hides a column and its input controls if the column has either a `tag:misd.isi.edu,2015:hidden` or `tag:isrd.isi.edu,2016:ignore` annotation. If a column has the `2016:ignore` annotation and the annotation is an empty array, `null`, or has the `entry` context, then the column is hidden.
Columns that are hidden/ignored are also added to the `defaults` parameter when submitting form data so that the sever will fill in those columns for us.
This feature is live on [synapse-dev](https://synapse-dev.isrd.isi.edu/~jessie/chaise/data-entry/#2/Zebrafish:Subject). The Zebrafish:Subject table has both `tag:misd.isi.edu,2015:hidden` and `tag:isrd.isi.edu,2016:ignore` annotations on the `ID` and `Sub-sequence` columns. The code can be pulled …
=> Hide columns in data entry app

data-entry/form.controller.js, data-entry/index.html.in
Cross-posted from #356:
> Columns with type `shorttext` now display the usual one-line, unresizeable text input. Columns with type `longtext` now use a resizable `textarea` with a default height of 5 rows and 100% width.
> This feature can be seen [here](https://dev.isrd.isi.edu/~jessie/chaise/data-entry/#4/rbk:testtoo), where the "testtoo" table features the following relevant column types: "Name" is `shorttext`; "Comment" is `longttext`; "Other" is `text`.
=> Support 'shorttext' and 'longttext' column types

data-entry/dataEntry.app.js, data-entry/form.controller.js
The following changes were made to correspond with [PR #47](https://github.com/informatics-isi-edu/ermrestjs/pull/47) in ermrestJS. Assigning to @howdyjessie for review. This code can be tested on my [dev machine](https://synapse-dev.isrd.isi.edu/~jchudy/chaise/data-entry/#2/Zebrafish:Subject).
This code should be merged when the corresponding code in ermrestJS is merged.
=> Changes to not rely on annotations.get()

data-entry/dataEntry.app.js, data-entry/form.controller.js
Per a conversation I had with @robes, I changed the `.includes(...)` function to `.contains(...)`. [Here](https://en.wikipedia.org/wiki/Element_(mathematics)#Notation_and_terminology) is the noteworthy information.
"Logician George Boolos strongly urged that "contains" be used for membership only and "includes" for the subset relation only."
=> changing the includes function to contains

viewer/annotations/annotations.controller.js, viewer/annotations/annotations.service.js, viewer/index.html.in, viewer/osd/osd.controller.js, viewer/viewer.app.js, viewer/viewer.css
This PR brings some new features to the Image Viewer app; it addresses issues #480, #481, #483, and #487.
- #480: 
- The annotations visible in OSD are now consistent with search results on the left panel. If an annotation appears/disappears on the left panel, it also appears/disappears in OSD, _but not the other way around_.
- Searching through annotations in the left panel is no longer instantaneous. Clicking the new search (🔍 ) button or pressing Enter while the search input is focused executes the search.
- Clicking the Reset button clears the search input, and all annotations become visible in both the left panel and OSD.
- #481: A new Show/Hide toggle button has been added above OSD. Clicking this button toggles the visibility of annotations currently displayed in the left panel.
- …
=> Sync annotation visibility from Chaise to OSD

Makefile, record-two/record.app.js, recordedit/context.js, recordedit/recordEdit.app.js, recordset/recordset.js, viewer/common/providers/context.js, viewer/viewer.app.js
This is related to informatics-isi-edu/ermrestjs#69.
For the record2, recordset, recordedit, and viewer apps, each of these apps now pass in a second argument, the app's name, in its respective `ermrestFactory.getServer(...)` call so that ermrestjs can append the app names to the relevant async calls.
**Question**: I currently store an app's name inside its `context` provider (`$rootScope.context` for record2), and then pass in `context.appName` into the `.getServer` call. Is this sufficient? Should I create a mapping in `common` so that app names aren't as closely coupled with each app's code? Another way?
=> Add app name param to .getServer() calls

common/utils.js, scripts/utils.js
@robes @jrchudy @RFSH @hongsudt @howdyjessie This commit fixes issue #490 by adding a polyfill for `startsWith` and `endsWith` function for strings.
It also removes a syntax error in utils.js regarding IE 11 browser error  **Multiple definitions of a property not allowed in strict mode**
=> Added a polyfill for string.endswith and string.startswith 

common/styles/app.css, record/assets/javascripts/app.js, record/assets/views/record.html
In order to customize the css for markdown, I added the `markdown-container` class to app.css. 
Record app will attach this class to the elements that are `markdown` typed and therefore they have the correct styles. Take a look at [this example](https://dev.isrd.isi.edu/~ashafaei/chaise/record/#2939/resource:markdown/id=123).
For now, the only css rules are, showing bullets in ordered and unordered lists. New rules can be added.
=> Add markdown-container to record app

.gitignore, .travis.yml, Makefile, git_version_info.sh
This **PR** allows to generate a **version.txt** file on `make install` using [git_version_info.sh](https://github.com/informatics-isi-edu/chaise/blob/git_version_info/git_version_info.sh). It contains the git log for **chaise** and **ermrestjs** version which is being used. 
You can browse this file in the browser using the **Chaise** App url *https://[CHAISE_URL]/chaise/version.txt*. 
The file **version.txt** looks like this
```
**************************CHAISE BUILD INFO******************************
BUILD DATE : Fri Aug  5 10:35:08 PDT 2016
CHAISE : git_version_info*ncommit 367de825223ec301c906713e09407684351a8fa7
Author: Chirag Sanghvi <csanghvi@appacitive.com>
Date:   Fri Aug 5 10:29:43 2016 -0700
added bower install in travis.yml
EMRESTJS : masterncommit …
```
=> Git version info

record-two/index.html.in, record-two/record.app.js, test/e2e/data_setup/config/record2.dev.json, test/e2e/data_setup/data/product/media.json, test/e2e/data_setup/schema/product-record.json, test/e2e/data_setup/schema/product.json, test/e2e/specs/record2/helpers.js, test/e2e/specs/search/data-independent/00-sidebar.morefilter.spec.js
Changes for issue #554. Related tables only show up when they have data and when the previous table has loaded.
These changes can be tested [here](https://dev.isrd.isi.edu/~jchudy/chaise/record-two/#1/legacy:dataset/id=269).
=> Empty tables

recordset/recordset.html, recordset/recordset.js, test/e2e/data_setup/schema/product.json, test/e2e/specs/recordset/helpers.js, test/e2e/utils/chaise.page.js
PR for issue #578 
Use `tag:isrd.isi.edu,2016:table-display` `page_size` annotation as the default page size. If it's not specified, set default page size to 25.
=> Use annotated page size for recordset tables

common/styles/app.css, common/table.js, common/templates/table.html, record-two/index.html.in, record-two/record.app.js, record-two/record.controller.js, test/e2e/data_setup/config/related-table-link.dev.json, test/e2e/data_setup/config/relatedTableLink.json, test/e2e/data_setup/data/product/booking.json, test/e2e/data_setup/schema/product-unordered-related-tables.json, test/e2e/specs/record2/helpers.js, test/e2e/specs/record2/related-table/03-record.related-table-link.spec.js, test/e2e/specs/record2/related-table/protractor.conf.js, test/e2e/utils/chaise.page.js
This PR addresses the following:
- using the `compact/brief` context for references in record2 for the related tables (#570)
- a link after the related tables that goes to recordset when there are more than 5 values
- a link after markdown content as well
- created DOM structure for different display types in record2 (#580)
I don't have a link to an entity that has a related table with more than 5 values associated. I did write a test that makes sure that is working properly though.
=> Compact brief

package.json, test/e2e/specs/recordedit/data-independent/add/protractor.conf.js, test/e2e/specs/recordedit/data-independent/edit/protractor.conf.js, test/e2e/utils/protractor.configuration.js
This **PR** addresses the issue #566 **Be able to test chaise with different chaise configs**.
To specify which config you want to use for your spec, set `chaiseConfigFilePath` in your **protractor.conf.js** file as follows.
```js
var pConfig = require('./../../../../utils/protractor.configuration.js');
var config = pConfig.getConfig({
// Change this to your desired filed name
configFileName: 'recordedit.dev.json',
page: 'recordedit',
setBaseUrl: function(browser, data) {
browser.params.url = process.env.CHAISE_BASE_URL + "/recordedit" + "/#" + data.catalogId  + "/" + data.schema.name;;
return browser.params.url;
},
// Specify chaiseConfigPath
chaiseConfigFilePath: 'test/e2e/specs/recordedit/data-independent/edit/chaise-config.js'
});
exports.config = config;
```
You also need to run the …
=> Added support to specify chaise-config to be used for a spec

Makefile, common/utils.js, record/record.app.js, recordedit/recordEdit.app.js, recordset/recordset.js, test/e2e/specs/detailed/data-dependent/00-search.result.column.spec.js, test/e2e/specs/detailed/data-dependent/01-result.detail.page.spec.js, test/e2e/specs/navbar/data-dependent/00-navbar.spec.js, test/e2e/specs/record/data-dependent/00-record.presentation.spec.js, test/e2e/specs/record/data-dependent/01-record.editbutton.spec.js, test/e2e/specs/record/data-dependent/02-record.createbutton.spec.js, test/e2e/specs/record/helpers.js, test/e2e/specs/record/related-table/03-record.related-table-link.spec.js, test/e2e/specs/recordedit/data-independent/add/00-record.add.spec.js, test/e2e/specs/recordedit/data-independent/edit/00-record.edit.spec.js, test/e2e/specs/recordset/data-dependent/00-recordset.presentation.spec.js, test/e2e/specs/viewer/data-dependent/00-viewer.presentation.spec.js
Fixes issue #581  by enabling the location hash change handling. 
To avoid any interference with Angular rotuing, the test-cases should specify following statement before doing a `browser.get`.
```js
browser.ignoreSynchronization = true;
```
=> Url routing

record/record.app.js, test/e2e/data_setup/config/record.dev.json, test/e2e/data_setup/config/related-table-link.dev.json, test/e2e/data_setup/schema/product-record.json, test/e2e/data_setup/schema/product-unordered-related-tables.json
Fixed test failures in record app tests after changes to associative table displaynames. This uncovered a bug in record where if the default page size was overridden because of an annotation, it would always use that value for subsequent tables without the annotation.
=> Fixed test failures in record app tests

common/table.js, common/templates/table.html
PR for #646 
Two types of click handling in record table: 1) when click on a row, redirect to the record app 2) when click on a hyperlink in the table, redirect to the link. If both redirect to html page, this is fine because (2) takes over. If hyperlink is a downloadable file, both action will fire. This is not desire. This PR fixes this problem. If table cell content is HTML, row click is disabled.
=> Distinguish row click and html link in record table

common/styles/app.css, common/table.js, common/templates/recordset.html, common/templates/table.html, doc/annotation.md, record/index.html.in, record/record.app.js, record/record.controller.js, record/record.css, recordedit/form.controller.js, recordedit/index.html.in, recordedit/recordEdit.app.js, recordset/recordset.html, recordset/recordset.js, scripts/facetsService.js, test/e2e/data_setup/schema/product.json, test/e2e/specs/record/helpers.js, test/e2e/specs/recordedit/helpers.js, test/e2e/specs/search/data-dependent/02-filters.upon.result.spec.js, test/e2e/utils/chaise.page.js
PR for #658 
- Add a CREATE button to out-bound foreign key columns in recordedit
- Click on the button to open recordedit in a new tab
- Added test cases
=> Recordedit: Add 'create' button to foreign key columns

Makefile, common/authen.js, common/utils.js, common/vendor/angular-cookies.min.js, record/index.html.in, record/record.app.js, record/record.controller.js, record/record.css, recordedit/form.controller.js, recordedit/index.html.in, recordedit/model.js, recordedit/recordEdit.app.js, test/e2e/specs/navbar/data-dependent/00-navbar.spec.js, test/e2e/specs/record/helpers.js, test/e2e/specs/recordedit/data-independent/add/00-recordedit.add.spec.js, test/e2e/utils/chaise.page.js
This PR addresses #667 and #669. These 2 issues combine to describe a workflow in which:
- A user goes to a Record page and clicks an Add Record link on one of the related tables.
- The link takes the user to the RecordEdit page, where the foreign key relationship between the the main entity on the Record page and the clicked related table is pre-filled.
To test:
1. Go to [this record](https://dev.isrd.isi.edu/~jessie/chaise/record/#1/legacy:dataset/id=4894) on Record app.
2. Click the `Add Record` link for the External Reference related table (at the bottom)
3.  The browser open the RecordEdit app in a new tab, and the url in the new tab should have a `?prefill=` query parameter in the url.
4.  The `id` column on the RecordEdit tab should have the rowname of the main entity from Record …
=> Add new record from Record to RecordEdit

common/table.js, common/templates/table.html
This PR fixes issue [Search modal has area that is not clickable](https://github.com/informatics-isi-edu/ermrestjs/issues/271) in ermrestjs. 
The problem was that the span which contained the markdowndidn't allow to bubble the click actions to the row above it.
I have enabled it and I am explicitly checking for if the target is an anchor or button tag don't bubble up or else propagate it as a row click event.
You can test he functionality for search modal [here](https://dev.gpcrconsortium.org/~chirag/chaise/recordedit/#1/experiments:sample) and recordset over [here](https://dev.gpcrconsortium.org/~chirag/chaise/recordedit/#1/experiments:sample)
=> Fixed issue 271 in ermrestjs

record/record.app.js, record/record.controller.js
This PR addresses the loading message appearing when there is 1 related table. I tested this in situations where there are multiple tables, 1 table, 0 tables, as well as entities with hidden tables to begin with.
=> Loading... message shows properly

record/record.app.js
session added as the start of the promise chain in record.app.js so that the session is available when reference needs to check for permissions.
This PR fixes issue #641.
=> Session fetched in record.app.js

record/record.app.js
Record page doesn't force the user to log in when the page should be publicly viewable.
=> Record error handling

recordset/recordset.js
Recordset grabs the session before the reference is fetched to make sure there is a session or not. This helps in cases where recordset may be viewable as a public page.
This PR resolves issue #763. Assigning to @shinyichen and mentioning @howdyjessie.
=> Recordset session

common/errors.js, recordedit/recordEdit.app.js, test/e2e/specs/navbar/data-dependent/00-navbar.spec.js, test/e2e/specs/record/data-dependent/00-record.presentation.spec.js
This PR addresses issue #722. When no session is find in `recordedit` it continues on rather than throwing a not found error. This will now properly error out when checking the ACLs for the returned reference.
I also removed the error code numbers from the error messages that show up in the modal.
=> Handle no session properly

Makefile
This PR fixes issue #761 . 
The reason the icon wasn't loaded was because recordedit page didn't had font-awesome.css included. The icons are dependent on that css.
This can be tested here https://dev.gpcrconsortium.org/~chirag/chaise/recordedit/#1/gpcr_browser:construct_gui/
=> Fixed issue #761, sort-icon not showing up in modal for recordset

record/index.html.in, recordedit/index.html.in
PR for issue #769 (requires https://github.com/informatics-isi-edu/ermrestjs/pull/286 to be merged)
Show entity displayname (tuple.displayname) as HTML.
Before:
https://cirm-dev.isrd.isi.edu/chaise/record/#1/Microscopy:Experiment/ID=20160914-H%26ENone-JAM-0
After:
https://cirm-dev.isrd.isi.edu/~jchen/chaise/record/#1/Microscopy:Experiment/ID=20160914-H%26ENone-JAM-0
=> Tuple.displayname is now HTML. Use html binding where it's used. #769

recordedit/form.controller.js, recordedit/index.html.in, test/e2e/specs/recordedit/helpers.js
This PR fixes #706. To help avoid an "editable" field for these FK fields in the future, I added `contenteditable=false` to the `div` for these FK fields and a test case that checks it's an uneditable `div` (instead of an unforeseen `input` field that would allow editing).
=> Make sure the FK popup modal only appears for pseudocolumns

record/index.html.in, record/record.app.js, test/e2e/data_setup/config/record.dev.json, test/e2e/data_setup/config/related-table-link.dev.json, test/e2e/specs/record/helpers.js
This PR addresses #776. It adds a "+" to related table headings if that table has more rows than the page size.
=> Fix related table headings count

common/ellipses.js, common/templates/ellipses.html, common/templates/table.html, recordset/recordset.html, test/e2e/specs/recordset/helpers.js
The ellipses directive was table cell based. This caused two problems 1) loading the table is slow because the ellipse code has to run for each cell in the table, which caused the problem addressed in #787, table appears blank when page initializes, and 2) clicking on the more/less link only expands/collapses content of one cell, but should expand/collapse the row #801.
This PR made ellipses directive row based, which addresses both issues.
=> Ellipses Fix #787 & #801

Makefile, common/templates/navbar.html, test/e2e/specs/navbar/base-config/00-navbar.spec.js, test/e2e/specs/navbar/base-config/chaise-config.js, test/e2e/specs/navbar/base-config/protractor.conf.js, test/e2e/specs/navbar/no-logo-no-brandtext/00-navbar.spec.js, test/e2e/specs/navbar/no-logo-no-brandtext/chaise-config.js, test/e2e/specs/navbar/no-logo-no-brandtext/protractor.conf.js, test/e2e/specs/record/data-dependent/00-record.presentation.spec.js, test/e2e/specs/recordedit/data-independent/add/00-recordedit.add.spec.js, test/e2e/specs/recordedit/data-independent/add/chaise-config.js, test/e2e/specs/recordedit/data-independent/add/protractor.conf.js, test/e2e/specs/recordedit/data-independent/edit/protractor.conf.js, test/e2e/specs/recordset/data-dependent/00-recordset.presentation.spec.js, test/e2e/specs/recordset/data-dependent/chaise-config.js, test/e2e/specs/recordset/data-dependent/protractor.conf.js, test/e2e/specs/viewer/data-dependent/00-viewer.presentation.spec.js, test/e2e/specs/viewer/data-dependent/chaise-config.js, test/e2e/specs/viewer/data-dependent/protractor.conf.js
This partially addresses #766 by fixing the tests for navbar and the `headInjector` service.
**headInjector tests**: These deal with the specs that say `"should load custom CSS and document title in chaise-config.js"`
- Added this spec to Record app tests
- Modified the existing specs in Viewer, RecordEdit, and RecordSet apps to directly test the `customCSS` and `headTitle` properties of `chaise-config.js` instead of only testing _if_ these properties existed in `chaiseConfig`
**Navbar tests**:
- There are now 2 `chaise-config.js`s to test the navbar's functionalities by setting or not setting various `chaiseConfig` properties. The specific set of properties is listed at the top of these configs.
Assigning to @jrchudy, tagging @shinyichen if she'd like to take a look as well.
=> Fix non-deterministic tests

recordedit/form.controller.js, recordedit/model.js, recordedit/recordEdit.app.js, test/e2e/specs/recordedit/data-independent/edit/01-recordedit.edit.spec.js, test/e2e/specs/recordedit/data-independent/edit/protractor.conf.js
This PR addresses #795. 
Upon submitting in edit mode, if the app sees no difference between `recordEditModel.rows` and `recordEditModel.oldRows` (new property created to store initial state of `recordEditModel.rows`), then the app does not perform the operation to update that row in ERMrest. Instead, it just redirects to the appropriate Record page.
=> RecordEdit: Redirect properly when submitting form with no changes

record/index.html.in, record/record.app.js, record/record.controller.js, test/e2e/data_setup/config/related-table-link.dev.json, test/e2e/data_setup/schema/product-unordered-related-tables.json, test/e2e/specs/record/helpers.js, test/e2e/utils/chaise.page.js
This PR addresses #823.
It adds a "Table Display" link to each Markdown related table, which allows the user to toggle that table between Markdown and tabular display.
I replaced the `ng-switch` logic in favor of `ng-show` because I didn't want Angular to remove and re-insert elements in the DOM every time the user toggled the display, which would cause a delay for the user.
Requesting a review from to @jrchudy and tagging @shinyichen as well. Also assigning this PR to @jrchudy because ZenHub doesn't allow filtering by Reviewer yet. :(
=> Toggle Markdown related tables to between markdown and tabular views

Makefile, recordedit/recordEdit.app.js
This **PR** fixes issue #859 .Recordedit app didn't include `bindHtmlUnsafe.js`, due to which some html columns were not being rendered in the modal.
Can be tested here https://dev.gpcrconsortium.org/~chirag/chaise/recordedit/#1/experiments:sample
=> Included bindHTMLUnsafe on recordedit page

.travis.yml, Makefile, package.json
This PR fixes issue #886. We had to split `make testall` into separate smaller jobs because Travis has a time limit of 50 minutes per job.
=> Split make testall into multiple jobs to avoid travis timeout

recordedit/index.html.in
This PR fixes issue #848 where you couldn't click on x button when you have selected a foreign key from modal on recordedit page.
The issue was with the class `form-control-feedback` which added a `pointer-events:none` css style. This property disables the element from firing any input events.
https://dev.isrd.isi.edu/~chirag/chaise/recordedit/#1/legacy:dataset
=> Foreign Key X button not clickable

common/styles/app.css, common/templates/table.html
This PR fixes issue #861. Img tags inside a td cannot overflow and get clipped according to the aspect ratio.
=> Recordset table image overflow

common/ellipses.js, common/styles/app.css, common/templates/ellipses.html
This PR fixes issue issue #899. The problem was with the ellipsis directive which was not registering to listen to rowvalue changes.
Whenever the table content was updated, the ellipsis code had to be rerun which wasn't being done.
Now there is an explicit watcher on the row-values, which is triggered on change in values.
Can be checked [here](https://dev.isrd.isi.edu/~chirag/chaise/recordset/#1/legacy:dataset@sort(id)?limit=15)
=> More Less issue in tables when paginated or searched

common/delete-link.js, common/styles/app.css, common/templates/delete-link/delete-btn.html, common/templates/delete-link/delete-link.html, common/templates/record.html, common/templates/recordset.html, common/templates/table.html, detailed/assets/javascripts/app.js, detailed/assets/views/detailed.html, record/index.html.in, record/record.app.js, recordedit/form.controller.js, recordedit/index.html.in, recordedit/recordEdit.app.js, recordedit/recordEdit.css, recordset/recordset.js, test/e2e/data_setup/config/recordset.dev.json, test/e2e/specs/record/helpers.js, test/e2e/specs/recordset/helpers.js, test/e2e/utils/chaise.page.js, viewer/viewer.app.js
This PR addresses #816. It converts our existing CSS-based tooltips to the more flexible [tooltip tool from Angular UI](http://angular-ui.github.io/bootstrap/versioned-docs/1.3.2/#/tooltip).
- The `tooltip` attribute in the `deleteLinks` directive has been removed in favor of applying UIB tooltips directly to the directive instead (and thus allow for customization on placement, `append-to-body` or not, etc.).
- Tooltips are appended to the `<body>` by default in each app (set via `.config` blocks) to avoid potential clashes with styles on the tooltips' parent elements. This can be reversed by setting `append-to-body` to `false` on a per-tooltip basis.
=> Change tooltips to use UIB tooltips

.travis.yml, test/e2e/specs/search/data-dependent/02-filters.upon.result.spec.js, test/e2e/specs/search/data-independent/00-sidebar.morefilter.spec.js, test/e2e/utils/chaise.page.js, test/e2e/utils/protractor.parameterize.js
This PR changes search app test cases to start using wait instead of sleep as mentioned in issue #853 .
=> Changed sleep to wait in search test cases

recordedit/form.controller.js, recordedit/recordEdit.app.js, test/e2e/specs/recordedit/helpers.js
This PR addresses #863.
This fixes the scenario when a timestamp column is null and the user is unable to toggle the AM/PM button. This is because in edit mode, when a timestamp column has a null value, the `meridiem` property of the timestamp column's model object is set to `null` as well, and the toggling logic breaks from there.
Synapse-dev has records with null timestamp values, example demo: https://synapse-dev.isrd.isi.edu/~jessie/chaise/recordedit/#1/Zebrafish:Behavior/ID=BhvZfCza20160815A1@sort(ID::desc::)
=> RecordEdit: In edit mode, set default meridiem if null timestamp column value

Makefile, common/utils.js, package.json, recordedit/form.controller.js, recordedit/index.html.in, recordedit/recordEdit.app.js, test/e2e/data_setup/config/recordadd-multi.dev.json, test/e2e/data_setup/data/multi-add/multi-add-table.json, test/e2e/specs/record/helpers.js, test/e2e/specs/recordedit/data-independent/add/00-recordedit.add.spec.js, test/e2e/specs/recordedit/data-independent/edit/01-recordedit.edit.spec.js, test/e2e/specs/recordedit/data-independent/multi-add/06-recordedit.add-x-forms.spec.js, test/e2e/specs/recordedit/data-independent/multi-edit/08-recordedit.multi-edit.spec.js, test/e2e/specs/recordedit/data-independent/multi-edit/protractor.conf.js, test/e2e/specs/recordedit/helpers.js, test/e2e/specs/recordset/helpers.js
This PR addresses issue #870, allowing the multi-edit functionality for the recordedit page. Recordedit expects a uri in the form of `.../t:s/<column-name>=<val>;<column-name>=<val>;...`. This will show however many records that the user defines in the uri. 
After submitting the data, the user will be shown the resultset view of the recordedit app rather than being redirected to recordset. This can be tested from [here](https://dev.isrd.isi.edu/~jchudy/chaise/recordedit/#1/legacy:dataset/id=9;id=10).
=> Multi edit for recordedit

recordedit/recordEdit.app.js, test/e2e/data_setup/config/recordadd-defaults.dev.json, test/e2e/data_setup/schema/defaults.json, test/e2e/specs/recordedit/data-independent/add-defaults/07-recordedit.defaults.spec.js
If a column of type `boolean` has a default value of false, it is properly set when creating records. This PR resolves issue #926.
=> Boolean default value is false

record/record.controller.js, test/e2e/specs/record/copy-btn/06-record.copybutton.spec.js
The copy button in `record` includes a limit in the generated url so that only the number of forms specified are created upon loading the `recordedit` app. This fixes issue #928.
=> Copy button creates 1 form

recordset/recordset.html
The edit link on `recordset` will show based on the user's permissions and `chaiseConfig.editRecord`. This is so a not logged in user won't see the edit button as well as user's who aren't allowed to modify records.
=> Edit link on recordset checks permissions

.travis.yml, common/utils.js, record/record.controller.js, recordedit/index.html.in, test/e2e/specs/record/helpers.js, viewer/index.html.in
This PR addresses #849.
The delete record link now takes the reference to the deleted record, gets the reference to the record's table, contextualizes this table's reference to compact, and then fetches its `appLink`.
This PR cannot be merged until informatics-isi-edu/ermrestjs#321 has been merged because it needs the new `reference.table.reference...` feature in ermrestjs.
=> Use appLink when deleting a record in Record app

recordedit/recordEdit.app.js
`Recordedit` was incorrectly setting integer and float values when they were null upon fetching the record. They should have been setting null if the value was not defined yet.
This resolves issue #954.
=> Recordedit float and integer

record/record.controller.js
This PR addresses issue #958. This PR requires that [this PR](https://github.com/informatics-isi-edu/ermrestjs/pull/330) be merged first. The changes in the corresponding PR in ermrestJS  expose the functionality that this PR is implementing.
This can be tested [here](https://cirm-dev.isrd.isi.edu/~jchudy/chaise/record/#1/Microscopy:Specimen/ID=20160920-mKDCrlf1IRES21d-GA-0). Clicking the `Add` link for `Genes` should bring you to an association table. Clicking the `Add` link for `Slide` should bring you to a related table without an association.
=> Add link in related tables is based on association reference as necessary

common/ellipses.js, common/templates/ellipses.html, common/utils.js
This **PR** handles the issue with performance related to the more/less behavior.
Initially it used to do polling to check for height changes for dynamic HTML elements like `image` and `iframe`. This used to take a lot of processing power.
Now, the code explicitly attaches `onload` event handlers onto these elements. This handler is called once the image and iframe is loaded and updates the height to add/removes the ellipsis.
You can test it on GPCR for recordedit . 
https://dev.gpcrconsortium.org/~chirag/chaise/recordedit/#1/experiments:experiment
**Image:** 
https://synapse-dev.isrd.isi.edu/~chirag/chaise/recordset/#1/Zebrafish:Behavior@sort(Image%20Date::desc::)
**Iframe**
https://synapse-dev.isrd.isi.edu/~chirag/chaise/recordset/#1/Zebrafish:Cropped%20Image@sort(Extract%20Date::desc::, …
=> Changed ellipsis implementation to use onload instead of polling

test/e2e/utils/chaise.page.js, test/e2e/utils/protractor.parameterize.js
This PR adds a separate method `performLogin` to `chaise.page.js` that performs login on behalf of a user when passed a cookie.
Documentation can be found [here](https://github.com/informatics-isi-edu/chaise/wiki/E2E-tests-guide#setting-webauthn-cookies-in-test-cases)
=> Added separate method in chaise.page.js to performlogin

common/styles/app.css, common/templates/recordset.html
This PR addresses issues #907 and #991. 
- The info button on recordset has been removed and the corresponding information from the tooltip is now present on the search button.
- The reset button has been removed in favor of having an `X` inside of the search input box with the same behavior.
=> Recordset search cleanup

recordedit/form.controller.js, recordedit/recordEdit.app.js
The tuples that are returned with the Page object from `Reference.read` in `recordedit` are copied and then attached to $rootScope for mutation. This prevents us from mutating Objects directly for submission purposes.
This PR resolves issue #994.
=> Deep Copy tuples in Recordedit

test/e2e/specs/recordedit/helpers.js
This fixes the error described in #995. 
The issue was that the browser driver would sometimes get the active element's ID before the `autofocus` directive was able to focus the search box in the modal. This resulted in the browser's active element to be the id of a boolean dropdown, which was the most recent active element.
The fix adds a `browser.wait` that waits for the active element's ID to be the search box's ID before proceeding with the expectation.
Turned on PR builds on Travis to make sure the tests also pass on Travis
=> Fix race condition in autofocus tests

common/authen.js
`Chaise` has been changed to use the standalone authn API. This change was made to the `authen` service that is used by all of the `chaise` apps except for viewer. When viewer is refactored to use the `Reference` API, this change will be reflected there as well.
I tested each login flow manually where the authn API endpoint is hit. This includes:
- when there is an existing session (fetching an existing session based on cookie storage)
- when the user comes to the app without a valid pre-existing session (clicking login) 
- when the user has their session expire while updating or creating (login popup window)
- when the user logs out of the application (clicking logout)
This PR resolves issue #298.
=> Standalone authn API

common/errors.js, common/utils.js, record/record.app.js, recordedit/recordEdit.app.js, test/e2e/specs/record/data-dependent/00-record.presentation.spec.js, test/e2e/utils/chaise.page.js
This PR addresses issue #964. `Record` app will notify the user (with a useful error message) when their filter doesn't return a row. This had been previously implemented in `Recordedit`, so the logic was factored out into the `ErrorService` and reused in both places.
This PR also includes a `constant` defined in `utils.js` called `textStrings` (name open to discussion) that will be where all of our strings will be defined so that they exist in one place. Simply put, this makes it much easier to track down the wordage for messages we output. This will provide one place to make changes to that wordage rather than in many. This will also make `localization` easier in the future (if we decide to provide that as well).
=> Record shows an appropriate message when no tuple is found

common/templates/recordset.html
This PR addresses issue #1010. The table directive in `recordset` will no longer show `"No Results Found"` before the data has finished loading.
=> No results doesn't flash before data loads

recordedit/recordEdit.css
This PR fixes the issue mentioned in this comment https://github.com/informatics-isi-edu/chaise/issues/921#issuecomment-284510136.
Recordedit page shows horizontal scrollbar even with very wide windows.
This was caused because of removing the `overflow:hidden` css from the table.
https://dev.isrd.isi.edu/~chirag/chaise/recordedit/#18988/product:accommodation
=> Added overflow:hidden to the table in recordedit.

test/e2e/data_setup/schema/product.json
In [ermerstjs#355](https://github.com/informatics-isi-edu/ermrestjs/pull/355), I updated visible columns heuristics. As I mentioned in #1009, some chaise test cases are applying logic and therefore these test cases are failing after the changes.
To work around this problem, I changed visible columns annotation for edit and create to be the same list of columns chaise test cases expect. With this change, chaise test suits pass locally with my ermrestjs PR.
=> add visible columns for product schema in edit and create contexts

Makefile
This PR addresses issue #986. The makefile now has a separate path for the `ermrestJS` build directory and the runtime directory. This is so that `chaise` can properly choose when to use the cached version of `ermrestJS`.
NOTE:
For my own local development on the dev servers, I have been using the following command to make `chaise` properly:
`make ERMRESTJS_DIR=../../ermrestjs/build all`
This changed the value of the `ERMRESTJS_DIR` variable for the make tasks to properly reflect my folder structure on the dev servers. I now use `make ERMRESTJS_RT_DIR=../../ermrestjs/build all`.
=> Makefile wasn't checksumming ermrestjs properly

Makefile, recordedit/form.controller.js, recordedit/index.html.in, recordedit/recordEdit.app.js, test/e2e/data_setup/config/recordedit-multi-column-types.dev.json, test/e2e/data_setup/data/multi-column-types/table_2.json, test/e2e/data_setup/data/multi-column-types/table_w_generated_columns.json, test/e2e/data_setup/schema/multi-column-types.json, test/e2e/specs/recordedit/data-independent/edit-multi-col-types/09-recordedit.types.spec.js
This PR addresses #1016. 
When a timestamp/timestamptz column is disabled, RecordEdit uses a disabled text input in the form, which was incompatible with the object structure used to represent timestamp-related values in the form.
To fix this, we won't apply any transformations on disabled columns so that they are simply the value received from ermrestjs.
=> Fix disabled inputs

views/ermretrieveresults.html
On my macbook pro (resolution 1280x00) the download ‘form’ in the results bar drops to a line below. This is a quick fix to make the selection field for the download format (CSV or JSON) narrower. If we add more formats with names longer than JSON, this might need to be reworked.
=> make the results more narrow

recordedit/recordEdit.app.js, test/e2e/data_setup/data/editable-id/editable-id-table.json, test/e2e/data_setup/schema/editable-id.json, test/e2e/specs/record/copy-btn/06-record.copybutton.spec.js
This PR addresses issue #1034. When a record is copied, the generated columns are no longer copied and instead it shows "Automatically generated" in the input field.
I adjusted the test cases to account for this scenario and added a column to the table for the copy tests that is generated.
=> Copy not generated columns

common/utils.js, recordedit/form.controller.js, recordedit/index.html.in
This PR addresses issue #1028. When the user submits a 'PUT' request via `Reference.update` and it returns a smaller set of data than what was submitted, `chaise` will properly display that information to the user.
For this to work, you have to have the proper permissions. [This link](https://dev.gpcrconsortium.org/~jchudy/chaise/recordedit/#1/assets:cpm@sort(last_modified_timestamp::desc::,id)?limit=25) is a link to my folder on dev.gpcr. 
To test this, follow the link above and submit the data. You should be able to change entities with `Site name` as `USC`. The 2 entities associated with `iHuman` shouldn't be editable.
NOTE: The following requires the changes to `ermrestJS` as well. The above does not rely on changes to `ermrestJS`. 
You can then follow [this …
=> PUT returns 200 with partial data

recordedit/recordEdit.app.js, test/e2e/specs/recordedit/helpers.js
This PR fixes issue #1039. There was a condition for when the page was initialized to set a default value for some fields (if it was available) in the `entry/create` context. If that default wasn't available (it's a function) or it's `null`, `timestamp` and `timestamptz` subfields were initialized to `null` with a default meridiem of `AM`. 
This was then being overwritten to the default value. That should have been nested in an `else` case.
=> Toggling AM/PM

record/record.controller.js, test/e2e/specs/multi-permissions/visibility/00-record.spec.js
This PR addresses issue #1055. The Show/Hide empty related tables toggle is now based on whether the user can modify at least one of the related tables. If they can, it shows all empty related tables by default.
=> Heuristics for when to show related tables changed

common/errors.js
This PR addresses issue #1064. Fixed check for `search` app as well. Because facebase uses the url pattern: `facebase.org/data/search` we can't be checking for anything but just the app name.
=> Hide catch all in viewer app

common/authen.js, common/navbar.js, common/table.js, common/utils.js, record/record.app.js, recordedit/form.controller.js, recordedit/recordEdit.app.js, recordset/recordset.js
This PR adds an explicit interceptor for handling 401 errors in `authen.js`.
Whenever a 401 error is encountered the handler is called. The handler renders the login window and on successful login, fetches the new session and sets it in the `authen` module.
It also adds logic to subscribe to change in session. This is used in navbar to update the once the user has logged in.
Can be tested here https://dev.gpcrconsortium.org/~chirag/chaise/recordedit/#1/experiments:experiment
=> 401 handling

recordedit/form.controller.js
This PR addresses [issue #374](https://github.com/informatics-isi-edu/ermrestjs/issues/374) in `ermrestJS`. 
`Chaise` uses the function on `ReferenceColumn` to check whether a column is a foreign key or not. [This PR](https://github.com/informatics-isi-edu/ermrestjs/pull/392) in `ermrestJS` has to be merged first.
=> isForeignKey checked based on ermrestJS function

record/index.html.in, record/record.app.js, test/e2e/specs/record/copy-btn/06-record.copybutton.spec.js
This PR addresses issue #1056. I added the test to the _copy_ spec because that spec relied on a schema where the main entity did not have any related tables.
=> Loading... text does not show up when there are no related tables.

recordedit/recordEdit.app.js, test/e2e/data_setup/config/record-copy-btn.dev.json, test/e2e/specs/record/copy-btn/06-record.copybutton.spec.js, test/e2e/specs/recordedit/data-independent/multi-edit/08-recordedit.multi-edit.spec.js
This PR addresses issue #1063. When copying a record, the reference displayname is shown so the entity title is `Create <table.displayname> Record`.
=> Recordedit copy uses reference displayname as entity title

common/validators.js
This PR addresses issue #1068. The date validator was being run after the data was submitted on a null date field.
=> Date validator doesn't run if the date obj is null

common/authen.js
This issue was found while trying to reproduce issue #1066. My comment mentions that in the issue.
The change I made looks like something we missed when we were making sure this didn't break `search`, `viewer`, or `login`.
=> Don't attach the 401 handler in ermrestJS to the logout page

recordedit/recordEdit.app.js
This PR addresses issue #1102. In `recordedit` we were creating a deep copy of the whole `page.tuples` array. This would recursively copy every single object in each `Tuple` in the array. This is unnecessary given that we are only ever modifying the data associated with the `Tuple`. I added a function to the `Tuple` class in ermrestJS to handle this so that the `Tuple`'s prototype can be used.
**NOTE: This PR cannot be merged until [this](https://github.com/informatics-isi-edu/ermrestjs/pull/405) PR is merged in `ermrestJS`.
=> Remove deep copy in recordedit

common/validators.js, recordedit/form.controller.js, recordedit/index.html.in, recordedit/recordEdit.app.js, test/e2e/specs/recordedit/data-independent/edit-multi-col-types/09-recordedit.types.spec.js, test/e2e/specs/recordedit/helpers.js
This PR fixes 2 issues, #1115 and #1116. 
The error reported in #1115 was happening because the value in another field (the disabled last modified field) was not being formatted properly for data submission. This has been addressed by not pre-formatting the view model for disabled timestamp fields (this is how issue #1116 was resolved). The other requested changes to the time input have been made as well.
The time input no longer limits the hour value from being restricted to 1-12. It allows the user to type a number from 0-23 for the hour. The time input no longer restricts the user to typing in `hh:mm:ss` format. They can enter in 1 OR 2 digits for each time field (hours, minutes, seconds). They can also leave off the seconds or even the minutes (`hh:mm` or `hh`).
=> Timestamptz bug

recordedit/recordEdit.app.js, test/e2e/data_setup/schema/recordedit/defaults.json, test/e2e/specs/default-config/recordedit/add-defaults.spec.js
This PR addresses issue #1128. The default values show properly in `recordedit` inputs when those values are defined and not a function, i.e. those values are most likely primitives (strings are primitives in JS).
We can discuss the logic tomorrow and decide whether that should be reorganized to make more sense. I had to add a bunch of comments because I had to re-understood the reasoning behind what was there.
=> Default values in recordedit show up properly if the input is disabled

test/e2e/utils/protractor.configuration.js, test/e2e/utils/protractor.import.js
This PR addresses issue #1150.
The schema configuration objects were refactored into their JSON documents and are represented by their file path in the test configuration object. When the test configuration is read in, it checks whether the schema configurations are strings (filenames) and reads in the contents of that file.
=> Catalogs not deleted after tests end

Makefile, common/utils.js, record/record.app.js, recordedit/recordEdit.app.js, recordset/recordset.js, test/e2e/specs/all-features-confirmation/recordset/presentation.spec.js, test/e2e/utils/chaise.page.js
This PR addresses issue #1105.
`Record`, `Recordset`, and `Recordedit` now set these properties when making requests to the server. e2e test cases pass locally for me.
=> added support for setting the wid and pid for each server request

record/index.html.in, record/record.app.js, record/record.controller.js, test/e2e/data_setup/data/product/accommodation.json, test/e2e/specs/all-features-confirmation/record/presentation.spec.js, test/e2e/specs/default-config/record/related-table-actions.spec.js, test/e2e/specs/default-config/record/related-table-link.spec.js, test/e2e/utils/chaise.page.js, test/e2e/utils/record-helpers.js
This PR fixes issue #1161.
The related tables were not showing up by default when the user could add/edit the entities in them if those tables were empty. This is fixed by moving the logic to the `run` block. How it was defined before, it was relying on `formController.canCreateRelated()` being called. When none of the related tables had entities in them, this function was never executed in the html and therefore never updated the state for the page.
=> Related tables show up properly when they are empty

recordedit/index.html.in, test/e2e/data_setup/data/product/accommodation.json, test/e2e/data_setup/schema/recordedit/product-add.json, test/e2e/data_setup/schema/recordedit/product-edit.json, test/e2e/specs/all-features-confirmation/recordedit/add.spec.js, test/e2e/specs/all-features-confirmation/recordedit/edit-delete.conf.js, test/e2e/specs/all-features-confirmation/recordedit/edit.spec.js, test/e2e/specs/default-config/record/related-table-link.spec.js, test/e2e/specs/default-config/recordset/add.spec.js, test/e2e/utils/chaise.page.js, test/e2e/utils/recordedit-helpers.js
In this PR,
- `testPresentationAndBasicValidation` function in `recordedit-helpers.js` has been changed to:
1. Select the given values instead of random values.
2. Only test the file types that are available.
3. Show better error messages.
4. Ignore the markdown test case. This test case currently is only clicking on the first `live-perview` button. And since this test case is going to change (because the feature is changed), I didn't wanted to spend time on fixing it.
- `testSubmission` function has been added to test submission in both edit and create in single and multi submission.
Related Issue #1153
=> Change recordedit test cases to validate submitted values

record/index.html.in, test/e2e/specs/default-config/record/related-table-link.spec.js
This PR addresses issue #1082.
Removed the unnecessary `ng-if` around the record display and now force the related tables to load only once the `recordValues` array is defined.
=> related tables load after record display

common/utils.js, record/record.app.js, record/record.controller.js, recordedit/recordEdit.app.js, recordset/recordset.js
I didn't completely remove the `parseURLFragment` function because viewer app is still using it. But we should avoid using this function.
The reason that recordedit is calling parser directly is that it is using filter to determine the app mode (create, edit, or copy) and the controller expects this decision to be made by page load (not after reference is resolved).
Needs [ermrest#445](https://github.com/informatics-isi-edu/ermrestjs/pull/445) changes.
=> Remove Duplicated Parser Logic

record/record.app.js
For a record which does not have related entities, the spinner was never set to off, as the spinner was set to off inside the for loop of related entities.
Now, the spinner display is set to off outside the for loop for related references, so that it works fine for the record which does not have any related references.
=> Fix for the spinner issue

common/authen.js
When using the new modal login window for the OAuth login flow, at the end you should see a login confirmation page, but instead, the URL is wrong and therefore the page is 'not found'.
This PR addresses this issue and now the path is framed dynamically using the `window.location` and the hard coding of `chaise` has been removed
=> Code changes to solve Login confirmation page 'not found' issue #1130

chaise-config-sample.js, common/styles/app.css, common/templates/footer.html
List adds line height in the footer therefore increasing the page length. This causes footer directive to keep changing the location of the footer.
Changed `line-height` to `padding`.
Issue #1204
=> Footer Flicker issue

common/templates/recordset.html, test/e2e/specs/all-features-confirmation/recordset/presentation.spec.js
The paging buttons are disabled on recordset when the number of rows is less than the page size.
Resolves issue #1219.
=> Disable Paging options

common/templates/errorDialog.modal.html
This PR addresses the verbose changes needed for the error modal window that is popped up when there are multiple records fetched in a record page.
=> Changes the verbose of the error modal page for multiple record error

common/modal.js, common/table.js, common/templates/recordset.html, recordset/recordset.js, test/e2e/specs/all-features-confirmation/record/presentation.spec.js, test/e2e/specs/all-features-confirmation/recordedit/add.spec.js, test/e2e/specs/all-features-confirmation/recordedit/edit.spec.js, test/e2e/specs/all-features-confirmation/recordset/presentation.spec.js, test/e2e/utils/chaise.page.js, test/e2e/utils/recordedit-helpers.js
This PR adds functionality to the `recordset` directive to put a full entity count for the current reference at the top of the table. This can be seen in the `recordset` app and the `recordedit` foreign key popup selector.
This addresses issue #878.
=> Rs aggregate count

common/styles/app.css, common/templates/ellipses.html
This PR adresses #1227 .
`ellipses` directive has been changed. All buttons now belong to `btn-primary` class.
_File Changed:_
- chaise/common/templates/ellipses.html
=> View button panel

common/ellipses.js, common/modal.js, common/recordCreate.js, common/styles/app.css, common/table.js, common/templates/ellipses.html, common/templates/searchPopup.modal.html, common/templates/table.html, test/e2e/specs/all-features/record/related-table-link.spec.js, test/e2e/utils/chaise.page.js
This PR will add the feature of disabling already selected entities in the pure and binary association multi add modal. For that I have to add a new callback to the table directive called `getDisabledRows` which will return a promise resolved with an array of tuples.
I made an attempt to refactor the addPopup to use it in recordedit as well as record, but I couldn't make it work and didn't want to spend more time on this issue. I added some comments so we can refactor it later.
[ermrestjs#534](https://github.com/informatics-isi-edu/ermrestjs/pull/534) is needed for testing this branch.
=> Disable Existing Associative entities in Multi Add

common/delete-link.js, common/ellipses.js, common/table.js, common/templates/recordset.html, common/templates/recordsetWithFaceting.html, record/index.html.in, record/record.app.js, record/record.controller.js, recordedit/form.controller.js, recordedit/index.html.in, recordedit/recordEdit.app.js
This PR adds a spinner (really is just changing the conditions for when to show a spinner) to `recordedit`, `record`, and `recordset` when a delete action is taken. This is true for when you select the delete action from a table on `recordset`/`record` and the delete link in the sub-navbar on `record` and the delete button on `recordedit`.
This PR is for issues #1342 and #1362.
=> Recordedit delete spinner

common/authen.js
This PR solves one of the problems mentioned in this issue https://github.com/informatics-isi-edu/chaise/issues/1366. 
When a user visits a page as an anonymous user and logs in, we identify this situation by checking whether a session was present previously when the user logged in. If not then reload the page.
https://dev.isrd.isi.edu/~chirag/chaise/recordset/#36720/product:accommodation
=> Reload the page once the user logs in, when the switch is from annoymous

record/record.app.js, recordedit/recordEdit.app.js, recordset/recordset.js
This PR adds removed context parameters like `pid` and `wid` back to the params passed to resolve. 
Now you will find them passed in the header names as `Deriva-Client-Contexteriva` 
https://dev.isrd.isi.edu/~chirag/chaise/recordset/#1/isa:dataset@sort(release_date::desc::,id)
This PR is dependent on https://github.com/informatics-isi-edu/ermrestjs/pull/556.
=> Added context header pid and wid back in the params

common/styles/app.css, record/index.html.in, record/record.css
This PR addresses issues #1381 and #1383.
`@media print {...}` was added to change some of the styling when print is used from the browser tools. This should make printing documents look better than before and remove the limitation that bound it to just the first page. 
Extra padding was added to the main container so that the `Loading...` text shows up in a better place now.
=> Media print rules added in CSS

.travis.yml, package.json, test/e2e/specs/default-config/recordedit/immutable-inputs.spec.js, test/e2e/utils/recordedit-helpers.js
The changes in this branch fix 2 of the tests that fail for us in travis. One of them was because of a syntax error where `=` (set operator) was used instead of the `==` (equality operator). 
The other case is because of some timezone not being used properly when getting data back from the database in Travis only.
=> changes to (maybe?) fix build problems

record/record.controller.js, recordedit/form.controller.js, recordedit/index.html.in, recordedit/model.js, recordedit/recordEdit.app.js, test/e2e/data_setup/data/fk-filter-pattern/main-entity-table.json, test/e2e/data_setup/schema/recordedit/fk-filter-pattern.json, test/e2e/specs/all-features-confirmation/recordedit/add.spec.js, test/e2e/specs/default-config/recordedit/domain-filter.spec.js, test/e2e/specs/default-config/recordedit/immutable-inputs.spec.js
This include changes to add $fkeys support to domain_filter_pattern. 
The changes that I made for each scenario are:
1. For edit/copy mode: Attach `linkedData` (data from foreignkeys) to `vm.foreignKeyData`. So it can be used for `filteredRef`.
2. For create mode: Generate extra requests to get the actual value of foreign keys that have default value (Show spinner and also make the add multiple button disabled).
3. For pre-fill mode: Pass extra information so we can get the actual value of the foreignkey, instead of passing all the values of that table (Show spinner and also make the add multiple button disabled).
4. changing the foreignkey: Update the `foreignKeyData`. If foreign key data is loading (default or pre-fill) ignore that and just use the user-selected value.
5. clearing a …
=> add $fkeys support to domain_filter_pattern

Makefile, record/record.controller.js
This PR addresses issue #1398.
There aren't any test cases that look for the url including a filter or facet blob so none of the tests had to be changed. Those tests instead verify the data being displayed on the page instead and that the prefill param worked properly.
=> Removed filters from add link

recordedit/recordEdit.app.js, test/e2e/data_setup/config/errors/config.json, test/e2e/data_setup/config/errors/dev.json, test/e2e/specs/all-features-confirmation/errors/errors.spec.js, test/e2e/specs/all-features-confirmation/errors/protractor.conf.js
This PR addresses #1405 .
- Recordset redirect link was missing in `recordedit` app and has been fixed in this PR.
- Test cases for redirect links have been fixed.
=> redirectlink missing in recordedit app

test/e2e/data_setup/schema/recordedit/defaults.json, test/e2e/specs/default-config/recordedit/immutable-inputs.spec.js
This PR adds tests to the immutable-inputs spec. This is to verify that even when a default is set, `recordedit` still shows "Automatically generated". This resolves issue [#562](https://github.com/informatics-isi-edu/ermrestjs/issues/562) in `ermrestJS`.
=> Tests for system column defaults in recordedit

test/e2e/specs/all-features-confirmation/errors/errors.spec.js
This PR adds just one phrase in the existing test case which was changed at `ermrest`. 
Text added in `test/e2e/specs/all-features-confirmation/errors/errors.spec.js`
=> error test case changed due to ermrest changes

common/ellipses.js, common/faceting.js, common/modal.js, common/styles/app.css, common/table.js, common/templates/ellipses.html, common/templates/faceting/choice-picker.html, common/templates/faceting/faceting.html, common/templates/list.html, common/templates/recordset.html, common/templates/recordsetSelectFaceting.html, common/templates/recordsetWithFaceting.html, common/templates/searchPopup.modal.html, common/templates/table.html, common/utils.js, test/e2e/specs/all-features-confirmation/recordset/presentation.spec.js, test/e2e/specs/delete-prohibited/recordset/ind-facet.spec.js, test/e2e/utils/chaise.page.js
This PR includes:
1. Adding "Records With Value" (not-null) option in the recordset selector for faceting. The logic for not-null filter is as follows:
-  In modal: If you choose "Records With value" all the selected rows must be deselected and all the rows should be disabled. Users should be able to click on `clear all`, `x` besides the "Records With Value", and also the checkmark for "Records With Value" to remove the filter. After removing it, all the rows should become selectable.
- In Facet panel: If you end up in the recordset with not-null filter, it should always show at the top of the list, and other options must be disabled. Deselecting it, should make all the other options enabled. If you select the not-null again, it should clear and disable all the other filters.
2. …
=> Facet Not Null Support

common/faceting.js, test/e2e/data_setup/schema/recordset/faceting.json, test/e2e/specs/all-features/record/related-table-link.spec.js, test/e2e/specs/delete-prohibited/recordset/ind-facet.spec.js
The assumption in the previous implementation was that the `tuple.uniqueId` and `filter.uniqueId` are the same, but that might not be the case. If the facet definition is not based on the shortestkey these two will be different values. I changed the choicePicker implementation to  store the whole tuple object, so we can extract the `tuple.uniqueId` which is needed for modal picker (it's used in the logic for `isSelected`).
I also added a test case to the faceting spec for this one, and fixed the condition of one of the test cases that was failing locally for me.
=> Fix Facet Based on Secondary Key Bug

record/index.html.in, test/e2e/specs/all-features-confirmation/record/presentation.spec.js
This PR addresses #1449 
Added **Main** link on the top of the list and renamed the header to **Contents**.
Test case is in [`presentation.spec.js`](https://github.com/informatics-isi-edu/chaise/compare/tocHeader?expand=1#diff-0c4175e21d5fe1dffc2ed1275f8a5798)
=> TOC header and Main link on the top

recordedit/form.controller.js, recordedit/index.html.in
This PR addresses issue #1435.
The issue was that the `main-container` was only part of the `recordedit` form input and not present when we saw the resultset.
Note: I changed the lines that some of the tags were placed on. We had tags that when too long, we put a return character so the code looked cleaner for editing. This made it really tough for the editor to help me with auto-indentation and verifying that the template was stable. If this is a continued issue, each developer can change their personal editor to have content wrap to the next line or not.
=> scroll on recordedit resultset view

common/authen.js, common/storage.js, common/utils.js
This PR addresses issue #1457. 
There are 2 values stored in the localStorage. 
```
localStorage.session = {
previousSession: Boolean (always true if key is defined),
promptExpiration: String (1 hour from when it is set/updated)
}
```
The prompt will only show if a user has logged into the system with that browser before. Once the user logs in, `previousSession` is set to true. Next time the user comes back to the system and they don't have a session, they will be prompted to login or to continue anonymously. If they choose to continue anonymously, an expiration token is set. 
If the user logs in again, this expiration token is deleted.
If the user explicitly logs out of the system, this whole object is removed 
(i.e.`delete localStorage.session`)
=> anonymous login popup only after a user has logged in

common/alerts.js, common/authen.js, common/templates/alerts.html, common/templates/recordset.html, common/templates/recordsetWithFaceting.html, common/utils.js, record/record.app.js, recordedit/index.html.in, recordset/recordset.js
The anonymous login prompt is no longer a modal popup but a soft alert warning that follows a similar set of use cases. This is for issue #1469.
The alert only shows up if a user has logged in before and had their session expire. 
- If the user logs out, it deletes the stored value that we check for when deciding whether to show the alert or not. 
- If the user does nothing with the alert, it will continue to show on each subsequent `record` and `recordset` page if the user doesn't login. 
- If the user clicks the `x` to dismiss the alert, it creates the expiration token and sets it to an hour from now
- If the user continues to make successful http requests, this expiration is extended to be an hour from now
=> Anonymous login alert

common/upload.js, test/e2e/specs/all-features-confirmation/recordedit/add.spec.js
This PR addresses issue [#616](https://github.com/informatics-isi-edu/ermrestjs/issues/616) in `ermrestJS`.
We were not using the returned url in `chaise` from the `ermrestJS` function that triggered on completion of the upload job.
Note:
The modified tests will only run in the local environment (file upload features are not tested in travis).
=> versioned url is used for the uri that is stored with asset data

common/templates/table.html, test/e2e/specs/all-features/recordset/permissions-visibility.spec.js
Added a conditional based on whether the user has permission to edit or delete anything on that reference. 
The only case this doesn't support is when a user has those permissions given to them by the reference but each row has row level security that prevents them from doing anything but view those rows. If this is true about every row displayed in the table, this will still display "Actions".
=> Rename action column header when only view is available

common/styles/app.css, record/record.controller.js, recordedit/form.controller.js, recordedit/index.html.in, recordedit/model.js, recordedit/recordEdit.app.js, recordedit/recordEdit.css, recordset/recordset.controller.js, test/e2e/specs/all-features-confirmation/recordedit/edit.spec.js, test/e2e/specs/all-features/record/copy-btn.spec.js, test/e2e/specs/all-features/recordedit/permissions-visibility.spec.js, test/e2e/specs/default-config/recordedit/multi-edit.spec.js, test/e2e/utils/chaise.page.js, test/e2e/utils/record-helpers.js, test/e2e/utils/recordedit-helpers.js
This PR adds the bookmark container to the `recordedit` app outlined in issue #1491. This is now consistent across each application.
Notes:
- `$timeout` wraps both setting the main container height and the footer styling
- this had to be done for weird cases where the bookmark container would load smaller than it should in `RE` then expand after the height calculation was set.
- `RE` has 2 bookmark containers.
- there would have been too many converse `ng-if=bool` and `ng-if=!bool` with 1 container
- displayname consistency in `RE`
- the `page-title` element now shows the entities `displayname`  if in single edit or a more default title in other modes
- the `page-subtitile` element shows the table name associated with the reference
=> Recordedit bookmark container

common/templates/recordset.html, record/index.html.in, record/record.app.js
This was already being done in `recordedit` because of the canCreate and canUpdate checks.
=> delay showing footer

common/table.js, record/record.controller.js, record/record.utils.js, test/e2e/specs/all-features/record/related-table.spec.js, test/e2e/utils/record-helpers.js
As I described in the issue, the fix was very simple. I created the PR mainly for the test cases.
In case of adding related entities that are not pure and binary, during e2e sometimes it fails to find the cookie and therefore it doesn't update the page. For now I am refreshing the page before testing, but we should investigate this. While testing it manually it always works.
In case of pure and binary, since we're not adding any cookies, it's working properly in e2e and manual testing.
=> update record after adding related entities

common/authen.js, common/errors.js, common/recordCreate.js
When records are created or updated, and we receive an error, we weren't checking to make sure the user still had an active session. When the user doesn't have an active session (and it's a conflict error... maybe this should be generalized but the use case was for a conflict error), we are now presenting a popup modal for them to go through the login flow.
Note: This reloads the page. There's some refactoring that needs to be done for the session service so this can work without reloading the page.
=> recordedit error check login state first

common/errors.js, recordedit/recordEdit.app.js
Upon merging PR #1544 to fix issue #1539, a bug was introduced. This created a broken login loop when an error should have been presented. This was found because the test cases stopped passing in travis.
This happened because of a generalization of the Conflict Error logic and if the user had a previous session. We originally decided (in the issue) to just apply this logic to the `recordedit` application. 
We thought it would make more sense to generalize this to all of the apps so that if a conflict error was reached from a different app (read request) we would handle it in a similar way (prompt the user to login first to verify if it was an issue because of their login state).
What this caused though, was a case where a terminal error was never being thrown if you got a conflict error …
=> common 409 bug

common/faceting.js, test/e2e/specs/delete-prohibited/recordset/histogram-facet.spec.js
It used to throw terminal error since we have not covered that case. I did a bit of refactoring to make it easier.
I tried to explain the error in the issue description. To summarize, in case of timestamp and null value, we were not setting values for `absMin` and `absMax` and that was causing problems.
=> handle null values for min and max in histogram

recordedit/recordEdit.css
This was required because by default, the table was assigned "max-width: 100%;" which prevented the horizontal scroll from being displayed. 
Tested this change on all browsers : Internet Explorer, Edge, Firefox, Safari and Chrome.
=> Added "max-width: none;" to the bootstrap table on Record edit page.

common/styles/app.css, common/templates/recordset.html
-Attached a custom class "filters-tooltip" to override max-width property assigned by "tooltip-inner" class of bootstrap. This will assign width based on the size of tooltip content.
=> Changed maxwidth of chiclet-tooltips

common/styles/app.css, common/templates/faceting/faceting.html, test/e2e/data_setup/schema/recordset/faceting.json, test/e2e/specs/delete-prohibited/recordset/ind-facet.spec.js, test/e2e/utils/chaise.page.js
This PR adds tooltips to facets. Two points of discussion here:
- The placement of facets. At first I went with `bottom`. The same way we are having it for the other parts of the facet panel. But the problem with having it in bottom is that if comment is long, it might go outside the viewport. I could hack it, but decided to go against it and change it to `right`. It's consistent with other tooltips that we're showing on the left side of the page (page title, facet toggle button). Most probably we are showing those on right for the same reason.
- Testing. At first I didn't want to test this like we are doing it in most places (just looking at the uib-tooltip attribute). But as @jrchudy pointed out, I could do the same thing that we're doing for testing permalink tooltips. That's what I …
=> add tooltips to facets

test/e2e/specs/all-features-confirmation/errors/errors.spec.js
Following modifications have been done to fix the issue : 
1. btn.click() was not getting registered in some cases so changed it to browser.executeScript("arguments[0].click();",btn);
2. Fixed chaining issues in some of the it blocks.
3. waitForElement(element) added in some of the failing test cases.
4. browser.ignoreSynchronization added for all describe blocks.
5. done() added in it blocks with chaining.
6. browser.refresh() added in the beforeAll() blocks of all the describe
blocks following a redirect to the recordset page. [This needs to be
investigated further]. This is the case where (sometimes) there is
timeout because on redirecting to the recordset page, it stays on the
app for too long causing the next describe block to fail.
7. Reordered the describe blocks for some fixing …
=> Error spec random failures resolved

Makefile, test/e2e/utils/protractor.configuration.js, test/manual/data_setup/config/config-recordset.json, test/manual/data_setup/config/dev-recordset.json, test/manual/data_setup/data/recordset/accommodation.json, test/manual/data_setup/schema/product-recordset.json, test/manual/specs/recordset.conf.js, test/manual/specs/recordset.spec.js
- Created a manual test for checking the placement of tooltips over column headers in the recordset app
- Added a command "make testmanually", in Makefile, to run manual tests 
- Updated  test/e2e/utils/protractor.configuration.js, to reuse its functions for specs in the manual test folder
- Updated documentation for the manual tests at https://github.com/informatics-isi-edu/chaise/wiki/Manual-UX-and-E2E-Testing#recordset---tooltip-on-column-headers
=> Manual test for checking placement of tooltips

common/errors.js, common/export.js
This PR changes the error sequence for export so that when an error occurs, it is shown to the user regardless of where on the page the user is looking. This is applied to most error cases for export (I didn't change the cancel case. If the user clicks cancel, it will continue to display an alert).
=> Export error modal

.travis.yml, common/faceting.js, common/table.js, common/utils.js, test/e2e/data_setup/data/faceting/main.json, test/e2e/data_setup/schema/recordset/faceting.json, test/e2e/specs/delete-prohibited/recordset/ind-facet.spec.js, test/e2e/specs/delete-prohibited/recordset/misc-facet.spec.js, test/e2e/utils/chaise.page.js
The [recent change in ermrsetjs](https://github.com/informatics-isi-edu/ermrestjs/pull/694) will break the existing test cases because the `jsonb` column types are not sortable in ermrestjs. I had to defined the `order` attribute for that facet.
Also I had to change the API call for getting the scalar values to pass the two new APIs that are added to faceting.
=> Facet order

Makefile, common/export.js, common/templates/export.html, record/index.html.in, record/record.app.js, recordset/index.html.in, test/e2e/data_setup/schema/record/product.json, test/e2e/specs/all-features-confirmation/record/presentation.spec.js, test/e2e/utils/chaise.page.js, test/e2e/utils/record-helpers.js
This PR adds export to `record` app. This adds a default download as CSV option that will always show up on `record` app now in the dropdown. If there is an existing export annotation for the table represented by the record page, the options defined by the annotation will show up in the dropdown menu.
A minor change also included was the use of `allowAnimations(false)` which can be called on any element found using protractor (angular) selectors. This removes the fade animation for when the modal is closed so that a click event that occurs in the next test case doesn't try to click on the modal or it's backdrop while it's fading out.
=> Record app export feature

common/navbar.js, common/templates/navbarMenu.html, test/e2e/specs/all-features-confirmation/chaise-config.js, test/e2e/specs/all-features-confirmation/navbar/no-logo.spec.js, test/e2e/specs/all-features-confirmation/recordedit/add.spec.js, test/e2e/specs/all-features/chaise-config.js, test/e2e/specs/all-features/navbar/base-config.spec.js
Refactored navbar so that parent menus can have urls and allow users to click that menu or any of it's child elements.
Added tests to test that opening in new tabs or the same tab works properly. Tests also test default `newTab` value and inheritance if `newTab` is undefined on a child.
=> Allow parent menu options to be links

record/record.utils.js
As the title suggests, we should update the main entity when we're updating the record page. It's a very simple change, but I'm not sure how we can actually test this.
=> update main entity on updating the record page

common/faceting.js, test/e2e/specs/delete-prohibited/recordset/ind-facet.spec.js, test/e2e/utils/recordset-helpers.js
This removes the null facet option from the check presence facet. This was missed when the other changes for issue #1655 were made.
=> remove null filter from check presence facet

common/table.js, test/e2e/specs/all-features-confirmation/recordedit/add.spec.js, test/e2e/specs/all-features-confirmation/recordedit/edit.spec.js, test/e2e/utils/chaise.page.js, test/e2e/utils/recordedit-helpers.js
Fixed a bug with table.js that would hide the table header for multi-create and multi-edit resultset view. This was introduced by the 400-QTE PR being merged into master when we removed one of the cases that "initialized" the columnModels.
=> Table header missing in recordedit resultset

.travis.yml, common/export.js, common/utils.js, test/e2e/specs/all-features-confirmation/record/presentation.spec.js, test/e2e/specs/all-features/chaise-config.js, test/e2e/specs/all-features/record/copy-btn.spec.js, test/e2e/specs/default-config/record/links.spec.js
This PR includes changes to support the changes in [ermrestjs#735](https://github.com/informatics-isi-edu/ermrestjs/pull/735).
I added two new test cases that are testing the default behavior (when export annotation is missing). One has the newly added chaise-config and the other one doesn't.
=> Export changes

common/errors.js, common/modal.js, common/utils.js
- Added a new CustomError type to the "Errors" factory
- Currently, the CustomError has 4 parameters for error header, message,redirectUrl and ok button message.
- Didn't add support for loginLink as session management is not implemented in any of the deriva webapps currently. Also didn't add subMessage and stack trace.
=> Support for Custom Error messages for deriva-webapps

recordedit/form.controller.js
After submitting the content in recordedit, the page will scroll to the top (before sending the request). This will show the user the alert notification that is displayed regardless of a success or error.
=> scroll to top after submitting 

common/errors.js, common/modal.js, common/templates/errorDialog.modal.html
- In the boolean-search app there is a requirement to dismiss the error modal on clicking the ok button
=> Use ok button to dismiss instead of redirect

common/styles/app.css, common/templates/record.html, record/record.controller.js, test/e2e/data_setup/data/editable-id/fk-table.json, test/e2e/data_setup/data/editable-id/html-name-table.json, test/e2e/data_setup/schema/record/editable-id.json, test/e2e/specs/all-features/record/copy-btn.spec.js
This PR adds the functionality for hiding the record app column headers as well as collapsing the table of contents panel by default.
Added a test case to an existing spec. Changed schema to add an inbound FK so that the ToC panel should be drawn in the page.
=> Record simple view

common/templates/delete-link/confirm_form_removal.modal.html, recordedit/form.controller.js, test/e2e/specs/default-config/recordedit/remove-edit-form.spec.js
- Made a new template for the modal to confirm removal of a record from the multi-record edit form
- Sample link: https://dev.rebuildingakidney.org/~divyatas/chaise/recordedit/#2/RNASeq:Experiment@sort(RMT::desc::,RCT::desc::,RID)?limit=25
=> Confirm form row removal modal

common/styles/app.css, common/templates/recordset.html
- The change in app.css solves the tooltip overflow issue (#1651) for custom filters
Sample Link - https://dev.rebuildingakidney.org/~divyatas/chaise/recordset/#2/Gene_Expression:Specimen/RID=N-H950;Stage_Ordinal=21;Stage_Ordinal=20;RID=N-GHRW@sort(Stage_Ordinal,RID)
- The change in recordset.html is to correct the format of tooltips for filters other than custom filters 
Sample Link - https://dev.rebuildingakidney.org/~divyatas/chaise/recordset/#2/RNASeq:Experiment/*::facets::N4IghgdgJiBcDaoDOB7ArgJwMYFM4gEEIwAXFAWwE8QAaELACxQEtck54QBzNKcsAA4BaDACMA1rACMAFiEA2ABoA5AEq0QAUQCyBAAoFYAJgDs8o1I08+gkROlylATnV1r-YWMmyFip9pAAXQBfEKA@sort(RMT::desc::,RCT::desc::,RID)
=> Overriding max-width of tooltip & removing space before comma in tooltip

common/table.js, record/record.controller.js, test/e2e/utils/record-helpers.js
We're updating the record page after users edit/create the related entities. But this is not happening for delete and we're only updating the table itself. This PR fixes this.
To do so, I just had to add a listener to record app for the event that ellipses directive sends when a rows is getting deleted. I also had to remove the event listener from table directive itself since the update is going to happen on the caller (record or recordset). I'm not sure why we had this listener in both table and recordset to begin with. Anyways, now the updating of table after create/edit/delete are handled the same way by the caller in both places (record and recordset) and not the table directive itself.
I cannot test this feature since the updating of other parts of the app is usually done by …
=> update record page on delete/unlink

common/utils.js, lib/login/login.app.js, lib/navbar/navbar.app.js, record/record.app.js, recordedit/recordEdit.app.js, recordset/recordset.app.js, recordset/recordset.controller.js
Made changes to enforce an idiom I think we should follow going forward. We should never directly consume `chaiseConfig` from the global scope. Instead, we should always make sure the `configProvider` sets the `chaiseConfig` on the `$rootScope`. 
In the cases that we need to rely on it outside of an angular app, make sure to check for `typeof chaiseConfig != 'undefined'` first. I added a new function to `ConfigUtils` so the `logProvider` can be set up properly.
=> apps work without chaise config

common/alerts.js, common/modal.js, common/templates/shareCitation.modal.html, common/utils.js, record/record.controller.js
Changes for this feature have been completed. When the user navigates to a record page, regardless of it being versioned or not, the share dialog will have both a live link and a versioned link. The headings for these links have been changed too.
Other smaller features include:
- If you load the record page to a live page then open the share dialog, a check is made to see if you are actually looking at the live content
- a notification will be shown if you are viewing out of date content
- Functions moved to a utility factory for re-ruse
- other changes made in corresponding [ermrestJS PR](https://github.com/informatics-isi-edu/ermrestjs/pull/767)
=> Changes to support proper live link with version when no version is present

common/navbar.js
- The catalog ID logic on line 40 was not handling the case when catalog ID was undefined
- Catalog ID is undefined if the navbar directive is being used in apps other than chaise like boolean-search
=> Handled the case when catalog ID is undefined

common/upload.js, test/e2e/specs/all-features-confirmation/recordedit/add.spec.js, test/e2e/utils/recordedit-helpers.js
This PR will fix the recent issue that we found in hatrac. All the code in hatrac to check whether we should start the next step was relying on counters. I changed all of those to check the booleans that we are already keeping track of. 
I also changed the job completion step to be serialized. Previously we were firing all these request at the same time, but now they will be fired after the previous one is completed.
The other change is how we're handling the existing files in the server. Previously we were firing a complete upload request immediately and we would skip the job creation/upload steps. But still when we would get to the last step, we were firing duplicated callbacks in ermrestjs to complete the job again. Now they will be treated the same in chaise, and in ermrestjs if the …
=> fix hatrac completion bug

common/authen.js, common/utils.js, viewer/viewer.app.js
The following are the three different places in chaise we're directly generating http requests. 
- Search app: 
It's relying on the old ermrestjs that resides in chaise. We cannot do anything about this.
- viewer app: 
There's a `getGoauth` function that is being called upon 401/404 error response while getting the session. Since it's using the `authen.js` this shouldn't even happen and the `authen.js` should handle this case. I'm not sure why this code path even exists in viewer app. Most probably we can just remove this code path (While I was fixing the viewer app I saw this config block and added a TODO with more details on why I think we should just remove it).  We should discuss about this
- `authen.js`: 
The login/logout requests. In this PR, I modified the $http in this file, to …
=> Use ermrestjs http service instead of $http

common/config.js, docs/dev-docs/config-app.md, lib/login/login.app.js, lib/navbar/navbar.app.js, record/record.app.js, recordedit/recordEdit.app.js, recordset/recordset.app.js, viewer/viewer.app.js
This PR will update the way we're including configuration app to make it more flexible. I moved all the dependencies to `config.js` and configuration app will only need to include `config.js`. This way if we decided to change any of the dependencies, we won't need to update other apps.
Also I couldn't find why we would need `ngAnimate` for config app. It wasn't included in recordedit any ways, so I just removed it and it works fine.
I also added a new doc to explain how other deriva-webapps should follow the same structure.
=> update config app + add documentation

common/errors.js, common/modal.js
Refactored the error flow a little bit so it's more consistent.
I moved all `$sce.trustAsHtml` calls for error messages to one place. Moved all message manipulation to the `handleException` function. Always add the `maybeShowLogin` message when the user is not logged in unless it's the `noRecordError` case, in which we show a different message.
@RFSH you mentioned in the issue that we should differentiate between the following 2 errors cases in `ermrestJS`:
- when the facet string is completely invalid (and therefore cannot be decoded) 
- when the facet string is correct but the generated path is invalid (possibly because user isn't authorized for parts of that path
Should this change still be made or do you think that distinction is not as important if we are _always_ going to show the …
=> Sugest login in error

common/errors.js, common/modal.js, common/recordCreate.js, test/e2e/specs/all-features-confirmation/record/presentation.spec.js
Opening this PR so we can have a discussion about the changes. 
The error case described in issue #1711 occurs when the user is fetching a template but there is no network connection. In the `chaise` apps, this can only occur _after_ a page has loaded, so the user had a network connection at one point but then lost it. The only time that we try to "fetch" templates after a page has loaded, is when a user clicks on an action that opens a modal instance.
I made changes to `modalUtils` to handle all of these cases. I'm using the navigator object API, [described here](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/Online_and_offline_events), to check the `onLine` property to determine what type of error case we are in. If the app is in an offline state, it will call into the …
=> No internet no templates

common/errors.js, common/modal.js, common/templates/errorDialog.modal.html, common/utils.js
This PR is an extension of issue #1461 . This changes the error behavior to show the error dialog instead of the login dialog. This is an extension PR #1785 .
The following is what it looks like when a 401 error is thrown while trying to download an asset:
@RFSH  The functionality changes in this PR can be reviewed. I still need to make sure with @hongsudt that the language is what we want.
Once this PR is ready to be merged, I will add the documentation for the new `chaiseConfig` property.
=> skip login dialog for 401 on asset

record/index.html.in, recordedit/index.html.in, recordedit/recordEdit.app.js, recordset/index.html.in, recordset/recordset.app.js, recordset/recordset.controller.js
This PR will add new classes to record, recordedit, and recordset that can be used for writing custom css in deployments.
The new classes are 
- `rs_s_<schemaName>` and `rs_t_<tableName>` for recordset.
- `r_s_<schemaName>` and `r_t_<tableName>` for record.
- `re_s_<schemaName>` and `re_t_<tableName>` for recordedit.
I added these classes because we wanted to change the recordset page of [this table in gudmap](https://dev.gudmap.org/~ashafaei/chaise/recordset/#2/Dashboard:Release_Status@sort(ID)). As you can see, using these new classes I'm only showing the table.
``` css
.rs_s_Dashboard.rs_t_Release_Status .faceting-resizable, 
.rs_s_Dashboard.rs_t_Release_Status faceting-collapse-btn,
.rs_s_Dashboard.rs_t_Release_Status #recordset-controls-container,
.rs_s_Dashboard.rs_t_Release_Status …
```
=> add app-wide class names

common/navbar.js
The navbar links will include the `pcid` and `ppid` if the link is to the same origin. The `ppid` will be set as `navbar` and the `ppid` will be the same as the one generated for the current page.
@RFSH  this can be reviewed, I'm not sure if I should add log info to the other navbar links/buttons (clicking the logo, clicking on the profile dropdown menu and it's subsequent options, or clicking the "return to live" button if looking at versioned data).
=> Log info added to navbar links

Makefile, common/config.js, common/utils.js, record/record.app.js, recordedit/mdHelp.app.js, recordedit/recordEdit.app.js, recordset/recordset.app.js
Moved the code to run in the config block so all chaise apps will set these properties. This came up because the deriva webapps don't honor the `customCss` property in chaise config.
@RFSH  I made this change really quick, but didn't spend much time thinking about how this would affect the functions called inside of `setupHead`. Everything should be fine (they all modify the document object) except the download click behavior function. 
I'm not sure if that function needs to be called after the angular app starts, or if that registers the on click behavior for any existing and newly created anchor tags with that class.
=> set up head in config.js

common/table.js, test/e2e/specs/all-features-confirmation/recordset/presentation.spec.js, test/e2e/utils/chaise.page.js
In this PR I made sure we're hiding aggregate column spinners when the data is null. 
Why this was happening:
In the current code, we are always sending requests for aggregate columns to ermrestjs, regardless of the returned value for main entity. The function to handle the value in chaise was assuming that the value will be an array, and would go over all the values and then would hide the spinner. But in case of null value for the main entity, the value is always an empty array and therefore the spinners would still keep spinning.
How I fixed it:
If the returned data for the main entity is null, we're not going to send extra requests for aggregate columns and we're hiding the spinner right away.
The change is very simple, but since the test is done locally, I wanted to announce the …
=> fix aggregate column spinners

common/recordCreate.js
The change for this was simple. If the `isModalUpdate` flag is true, we know we are in `record` app. This might not be the best way to test for this if `isModalUpdate` gets used in other app contexts later. I was thinking I could check the log action but don't want to tie log actions together with other functionality of our app.
I'm not sure if it's possible to test this error because of our disabled rows function.
=> Error dialog on pure and binary add error

common/table.js, common/templates/table.html, common/templates/tableHeader.html
After the main read in recordset table is done, we're generating requests for aggregate columns based on the active list. Also if we have to show more than 500 cells, we're going to gradually populate `rowValues` object. Now if we receive the response for aggregate columns before populating the object, it will result in a terminal error.
To fix this, I introduced a new object called `pendingRowValues`. The purpose of this object is hold onto the row values while we're waiting for the `rowValues` to be completely populated. I also added a new function that the "push more rows" will call to merge the two objects.
=> fix race condition in afterReadAggregate

common/inputs.js, common/styles/scss/_recordedit-app.scss, common/templates/inputs/inputSwitch.html, recordedit/form.controller.js, recordedit/index.html.in
This PR fixed an issue that @ljpearlman found in `recordedit` with boolean dropdowns being clipped when they are the last input field.
I added `dropdown-append-to` for boolean inputs so they are attached to the input container outside of the table (which has `overlow: hidden;`). I added a click event to the dropdown toggle element to recalculate the width of the dropdown each time it's opened because the number of forms can change.
This can be tested here:
https://dev.rebuildingakidney.org/chaise/recordedit/#2/Common:Principal_Investigator
=> Boolean dropdowns can flow outside of container

common/ellipsis.js, common/styles/scss/_recordset.scss, common/templates/ellipsis.html
The changes in #1883 have broken the "view details" links in recordset (and potentially other row-level buttons). Even when chaise is updating the row values (whether because of page, filter, or any other change), the "view details" links remain the same.
We should investigate this and create another PR. For now, I'm just reverting the change.
=> Revert "Truncation one more time"

common/faceting.js, test/e2e/specs/delete-prohibited/recordset/ind-facet.spec.js
The function that was responsible for syncing the checkboxes was not properly working. It had two flaws:
-  was assuming that the not-null choice is always available;
- and also wouldn't clear the not-null filter if it was selected. 
I modified the function to properly take care of the not-null and the rest of the options.
=> fix range picker bug related to clearing facets

common/table.js, common/templates/tableHeader.html, test/e2e/specs/all-features-confirmation/recordset/presentation.spec.js, test/e2e/utils/chaise.page.js
Removed the text `(custom)` when a `?limit=X` query parameter is present in the url. The custom page size is now also sorted properly in the dropdown.
=> Remove custom page limit text

common/templates/inputs/inputSwitch.html, common/upload.js, recordedit/form.controller.js, recordedit/index.html.in, recordedit/recordEdit.app.js
This PR was first introduced to fix the #1932 issue but since I was working on recordedit, I did some other refactoring as well. The changes are:
- Modified the select-all implementation regarding asset columns which fixed the #1932  issue. To make the implementation simpler, recordedit was using the simple disabled input for all the "select-all" forms, including assets. But this means that the `rows` value had to be a simple string and couldn't be the object that we store for assets. To solve this issue, recordedit was abusing `submissionRows` to hold the object. But this had an impact on other columns, and it was buggy. The code assumed that `sumbissionRows` is only populated after submit but that's not necessarily the case. For example, in the case of foreignkey pickers, we need …
=> Refactor recordedit codes related to select all and uploader

common/config.js, common/navbar.js, common/styles/scss/app.scss, common/utils.js, lib/login/login.app.js, lib/navbar/navbar-app.md, lib/navbar/navbar.app.js, lib/navbar/sample-navbar.html
This PR is part of #1936. The changes include:
- Modified the config app to use the new ermrestjs parameter to skip fetching of the schema object.
- Added css classes that can be used to hide the content of the page while navbar is loading.
- Added some checks to places that we're dynamically loading files so if we've already prefetched them (included in HTML file), we're not fetching them again.
This is part of the incremental changes that are required for #1936. Other changes will be added later as part of other PRs.
=> navbar app improvements

common/ellipsis.js, common/recordCreate.js, common/table.js, common/templates/table.html, test/e2e/specs/all-features-confirmation/chaise-config.js, test/e2e/specs/all-features-confirmation/record/presentation.spec.js, test/e2e/specs/all-features-confirmation/recordset/presentation.spec.js, test/e2e/specs/all-features/record/related-table.spec.js, test/e2e/specs/delete-prohibited/navbar/catalog-chaise-config.spec.js, test/e2e/specs/delete-prohibited/record/no-delete-btn.spec.js, test/e2e/specs/delete-prohibited/recordset/ind-facet.spec.js, test/e2e/utils/chaise.page.js, test/e2e/utils/record-helpers.js
- Go to a record page that has a pure and binary table.
- Click on "add" button to open the modal.
- Select a facet, so the number of rows that will be displayed after is less than the current number of rows.
- Chaise will throw a terminal error
(Sorry in advance for the following wall of text. I tried to explain it with as much detail as possible.)
When the data changes, we're first setting the value of `vm.page`, and then later in the promise chain, we will populate the values of `vm.rowValues`.
- `vm.rowValues` is what's displayed in each row of a recordset table.
- `vm.page` is used the `tuple` object that is used in ellipsis directive.
So what's displayed on the page won't change until we have populated the `vm.rowValues`. In the case of a normal recordset page, the logic to populate …
=> remove trackby to rerender ellipsis on every data update

Makefile, common/utils.js, viewer/viewer.app.js
This PR will add `OSD_VIEWER_REL_PATH` to parameterize the osd-viewer location. Since it's using `mview.html` (as opposed to `index.html`), this should be merged with [this PR in osd-viewer](https://github.com/informatics-isi-edu/openseadragon-viewer/pull/21)
=> add new env variable for viewer

.travis.yml, common/login.js, common/templates/login.html, test/e2e/specs/all-features/navbar/base-config.spec.js, test/e2e/utils/protractor.parameterize.js
Changed default display value of the displayed user information in top right corner. Previously this was displaying `display_name` by default which would show a string that looks like an email address. When `full_name` is not available, `display_name` is still used for the display value. 
A tooltip was also added when the user hover's over their user name. The tooltip will only be added if the user has a `full_name` defined so hovering over it shows more information (`full_name` and `display_name`)
Added a test for this in one of the navbar specs.
=> Change default user display name

common/styles/scss/_record-app.scss
This PR includes the following fixes
- Applying the thumbnail to the YouTube video on print was complicated as the styles are applied via YouTube and we have limited access to it. Hence, the alternative was to display a note informing the user that the video is hidden during print and possibly provide the URL of the hidden video.
=> Hiding iframe and video markdowns during print

Makefile, common/modal.js, common/styles/scss/_viewer-app.scss, record/index.html.in, record/record.controller.js, viewer/annotations/annotations.controller.js, viewer/annotations/annotations.service.js, viewer/constant.js, viewer/index.html.in, viewer/osd/osd.controller.js, viewer/viewer.app.js, viewer/viewer.utils.js
This PR will,
- Add a spinner to the share button to signal users that we're waiting for the popup (in both record and viewer app).
- Introduce a new method of passing annotations to osd viewer by using messages (instead of URL parameter).
- Fix the `Image_Annotation` read request to properly send multiple requests (instead of assuming there will be less than 200 rows).
- Display spinner for the screenshot button based on changes in [osd viewer#40](https://github.com/informatics-isi-edu/openseadragon-viewer/pull/40) PR.
- Change the color of buttons in the annotation sidebar to be aligned with the rest of the chaise buttons.
=> Viewer app improvements

chaise-config-sample.js, common/styles/scss/_navbar.scss, common/templates/navbar.html, common/templates/navbarMenu.html, docs/user-docs/chaise-config.md, test/e2e/specs/all-features/chaise-config.js, test/e2e/specs/all-features/navbar/base-config.spec.js
This PR adds functionality to the navbar to include dropdown header options. The structure will look like the following in the chaise config property `navbarMenu`:
```
"children": [{
"name": "A header",
"header": true
}, ...
```
Other changes included:
1. I found a failing test in one of the navbar specs where a menu option wasn't showing properly. ~~After looking at the code, I realized I implemented `canShow` and `canEnable` for the navbar menu options and sub menu options. I used `canEnable` for each of the `ng-if` conditions and never used `canShow`.~~
2. Modified the condition for the case that we wanted a url link. If there is no url defined, the link won't show at all.
3. Added more information to `chaise-config.md` pertaining to the order that chaise configurations are …
=> Dropdown headers

common/ellipsis.js, common/inputs.js, common/modal.js, common/recordCreate.js, common/styles/scss/_viewer-app.scss, common/table.js, common/utils.js, docs/user-docs/logging.md, record/record.app.js, recordedit/form.controller.js, viewer/annotations/annotations.controller.js, viewer/annotations/annotations.js, viewer/annotations/annotations.service.js, viewer/constant.js, viewer/index.html.in, viewer/osd/osd.controller.js, viewer/viewer.app.js, viewer/viewer.utils.js
This PR,
- Adds proper log support to the viewer app (#1910). For the complete list of actions please [refer to this google sheet](https://docs.google.com/spreadsheets/d/1cHhPR0AacvuH2o3QavWlJCIIyPajfn93fJzFnc7VA5M).
- Add extra log info to distinguish between view button and the rest links (#1917)
- Fix a bug in the viewer app which would cause users to be stuck in the edit form (Open edit form for an annotation, don't change anything and click on save.)
- Unhighlight annotations when switching to edit mode. 
- Removed the unnecessary usage of `slide_id` in the code.
- Fixed a small bug in the logic of disabling the "show/hide annotation" button. It wasn't properly checking the value that osd viewer is returning.
=> Logging support for viewer app

common/recordCreate.js, recordedit/index.html.in, test/e2e/data_setup/data/product/person.json, test/e2e/data_setup/schema/recordedit/product-person.json, test/e2e/specs/default-config/recordedit/composite-key.spec.js, test/e2e/specs/default-config/recordedit/multi-col-types.spec.js, test/e2e/specs/default-config/recordedit/remove-edit-form.spec.js, test/e2e/utils/chaise.page.js
If any of the foreign key column values had a falsy (`0`, `false`) value, recorddeit was ignoring them. This PR will fix that. 
I also modified our existing composite foreign key test case to test this.
**Created this PR just to make sure everything is stable on travis**
=> Fix a bug in recordedit where it would ignore falsy values

.travis.yml, common/styles/scss/_recordset.scss, common/templates/recordset.html, package.json, test/e2e/data_setup/schema/recordedit/fk-filter-pattern.json, test/e2e/specs/default-config/recordedit/domain-filter.spec.js, test/e2e/utils/chaise.page.js
In [ermrestjs#860](https://github.com/informatics-isi-edu/ermrestjs/pull/860) I modified the domain filter support to use `customFacets`. And this PR will modify how `recordset.html` is processing the `customFacets` property so it can properly display the custom facet used in domain filter. 
Please refer to the ermrestjs PR and issue for more information.
Other changes in this PR:
- Modifying test cases to test the new syntax and UI.
- Remove the unused `closureCompiler` dependency from `package.json` (it's deprecated and was complaining while I was using node 14.)
=> Domain filter changes

chaise-config-sample.js, common/navbar.js, common/styles/scss/app.scss, common/templates/navbar.html, common/templates/navbarMenu.html, test/e2e/specs/all-features/chaise-config.js, test/e2e/specs/all-features/navbar/base-config.spec.js
Added markdown name support to navbar menu and submenu options. This allows for markdown patterns to be defined to attach extra attributes (including class) to the element being defined.
=> Markdown name support for navbar options

common/authen.js, common/errors.js, common/utils.js, viewer/constant.js, viewer/viewer.app.js, viewer/viewer.utils.js
This PR will modify the viewer app so it's more aligned with the recent changes in RBK. Summary of changes are:
- Use the value of `Pixels_Per_Meter` column in the `Image` table for  `meterScaleInPixels` if it's missing from the page query parameters.
- Use the value of `URL` column in the `Consortium` table (it's a foreign key column in `Image` table) for  `waterMark` if it's missing from the page query parameters.
- If channel information is missing from the page query parameters, we will try to retrieve them from the `Process_Image` table. If it was missing from this table, we will fallback to `Image_Channel`.
Based on this, these are the newly added assumption (configurations):
`Image` table:
- Has a `Pixels_Per_Meter` column (the name is configurable.)
- Has a visible foreign key …
=> Viewer app configuration changes

common/inputs.js, common/recordCreate.js, common/templates/inputs/inputSwitch.html, recordedit/form.controller.js, recordedit/index.html.in, test/e2e/data_setup/schema/recordedit/product-person.json, test/e2e/specs/default-config/recordedit/composite-key.spec.js, test/e2e/utils/chaise.page.js, test/e2e/utils/recordedit-helpers.js
Changed input utils to format boolean values based on `column.display.preformatConfig` if it is present. This was only an issue in recordedit which didn't show the pre-formatted boolean values in the dropdown. This also applies when reading data in for edit mode. Before submitting the data to ermrestJS for create/update, we have to convert the "formatted" value back to the raw boolean value. This can be tested here:
https://dev.rebuildingakidney.org/~jchudy/chaise/recordedit/#2/Common:Collection/
I think it makes sense to do this in chaise since it applies to the display of the content.
=> Preformat boolean

common/errors.js, common/modal.js, common/navbar.js, common/styles/scss/_navbar.scss, common/templates/navbar.html, common/utils.js, test/e2e/data_setup/config/record/links.config.json, test/e2e/specs/all-features-confirmation/chaise-config.js, test/e2e/specs/all-features-confirmation/errors/errors.spec.js, test/e2e/specs/default-config/record/links.spec.js, test/e2e/specs/delete-prohibited/record/no-delete-btn.spec.js
I modified go to RID function to send a head request to the server first to see if the resource exists before trying to navigate there. If the server returns 405 (not allowed), we know the RID exists and should continue with navigating the user to the record page with the input RID.
I added a test that only runs locally to verify the resolver is working properly with a valid RID input into the RID search box. I modified the other test to run in both cases since locally catalog 4 shouldn't exist and in travis the resolver isn't configured even though we have the chaise config property (`resolverImplicitCatalog` set). Both of these cases should throw a warning message.
=> Handle 404 for rid search input

common/styles/scss/_markdown-container.scss
Styles added to chaise stylesheets to add a fullscreen button to the top right of all iframes generated using the iframe template in markdown. This also adds styles to hide that button when the `fullscreen-off` class is attached to the encompassing `<figure>`.
=> Iframe fullscreen button

test/e2e/data_setup/config/record/links.config.json, test/e2e/specs/all-features-confirmation/errors/errors.spec.js, test/e2e/specs/all-features/recordedit/permissions-visibility.spec.js, test/e2e/specs/all-features/recordset/permissions-visibility.spec.js, test/e2e/utils/chaise.page.js, test/e2e/utils/protractor.import.js
This PR will add e2e test for making sure the session expired alert is displayed. To achieve this,
- I had to modify the `performLogin` function that we have to modify the `localStorage`. 
- Since as part of the test I'm performing a logout. I have to make sure anonymous users can see the data. So I made sure test catalogs are readable by anyone. I could make this specific to only one spec, but I feel like this is actually a good change that we should have done a long time ago. We're not doing any testing based on user ACLs so there really is no need to hide the catalogs. That being said, this change might have an effect on CI e2e which I have not anticipated. If that's the case, I have to think about other ways of doing this.
- Added two tests to the errors spec. These two tests open a …
=> Test the session expired alert

record/record.app.js, recordset/recordset.controller.js
This PR changes recordset to use `replaceState` instead of `location.replace` (see attached issue for explanation on both). We also decided to add `pending...` into the head title in record app when we the reference has been resolved but the read request has not returned yet.
Looking at the code some more I found that we wrote a function called `setLocationChangeHandling` that listens for the url to change and checks if the change was made from internally or not to decide if the page should reload. This was because we were using the function `location.replace` which forces a page reload. Changing this to `replaceState` stops the need to update `$rootScope.location` to force `setLocationChangeHandling` to be called to not reload the page. 
I should clarify that there are 2 meaning of …
=> Consistent history

common/config.js, common/utils.js, docs/dev-docs/config-app.md, help/help.app.js, lib/login/login.app.js, lib/navbar/navbar.app.js, lib/switchUserAccounts.app.js, record/record.app.js, recordedit/mdHelp.app.js, recordedit/recordEdit.app.js, recordset/recordset.app.js, scripts/app.js, scripts/controller/ermrestLoginController.js, viewer/viewer.app.js
This PR changes the way each app interacts with the configuration app. It changes the constant `appName` to `settings`. It's now an object that has 3 properties (`appName`, `disableHeadTitle`, `disableOnclickBehavior`). Each of these are explained in further detail in `config-app.md`.
Made changes to each individual `app.js` file. I think only navbar app and login app should refrain from modifying the head title and the onclick behavior of links (even thought they relay on specific classes being defined).
Appropriate changes will be made in deriva-webapps to booleansearch, lineplot, and plot app (the three that currently integrate with config.js from chaise).
=> Change configuration app constant name

viewer/osd/osd.controller.js, viewer/viewer.app.js, viewer/viewer.utils.js
This PR will add the required functionality for [osd viewer#86](https://github.com/informatics-isi-edu/openseadragon-viewer/pull/86). This includes,
- A new function that will allow users to change the value of default z index in the database.
- A new `acls` parameter that only includes `canUpdate` for now to signal osd viewer that users can update the Image data in database.
=> Save default Z Index

common/config.js, common/export.js, common/navbar.js, common/utils.js, viewer/index.html.in, viewer/viewer.app.js
Viewer app is currently used in an iframe in the record page. So users can click on the "share" button for any of the annotation and by clicking on the link, the iframe (and not the whole page or new tab) will navigate to the "Image Annotation" table.
This is confusing as users don't have a proper way to get back to the previous page. And also they might think that clicking on "share" in the record page and navigating to that link should show the current state of the page (with "Image Annotation" record being in the iframe and not the viewer app).
I know that for now we want a solution that is limited to viewer app. But I didn't want to implement this just for the viewer app. So the actual implementation is independent of the app. And then using the config `settings` constant I'm making …
=> Change behvaior of links in viewer when inside an iframe

Makefile, recordedit/recordEdit.app.js, viewer/viewer.app.js
I did this for two reasons:
- Spectrum relies on jQuery and we don't want our shared vendors to be jQuery dependent since navbar is using it and navbar app is injected in static sites (where jQuery is not included or might clash with our version.)
- Other input-switch related dependencies are in viewer and recordedit. So there's no reason for this dependency to be in shared vendor.
Review is not necessary and I created this PR to make sure CI test cases are stable.
P.S. as part of this I also removed ui-select from chaise apps since we're not using it at all. I left it for the login app since it's included in app.js and I didn't want to modify that file.
=> Move spectrum to viewer and recordedit instead of shared vendor

common/errors.js
Required changes for the [ERMrestJS#879 pull request](https://github.com/informatics-isi-edu/ermrestjs/pull/879). To summarize:
- Added `contextHeaderParams` input to `logError` (used to terminal errors) to properly log `cid`, `wid`, and `pid` as part of it.
- Added support for the newly added `InvalidServerResponse` error
=> handle invalid server response error thrown from ermrestjs

common/styles/scss/_markdown-container.scss
Issue - https://github.com/informatics-isi-edu/chaise/issues/2105
Example of current behavior - https://www.gudmap.org/chaise/record/#2/Common:Collection/RID=17-3ZTY
Here the figures should have a list below
=> 2105 hide bullets

common/export.js, common/templates/export.html, test/e2e/data_setup/schema/record/editable-id.json, test/e2e/specs/all-features/record/copy-btn.spec.js
With the changes described in https://github.com/informatics-isi-edu/ermrestjs/pull/897, `csvDownloadLink` might not be available. So In this PR I modified the code to handle this.
This PR will also disable the button if both the export templates as well as `csvDownloadLink` are empty.
It's a very simple change but I decided to create this PR just for history.
issue: #2100
=> Handle empty csvDownloadLink and template list

common/templates/recordset.html
Changing the width of facet panel doesn't properly change the size of top-panel as well.
This is cased because in recent changes I changed `ng-show` to `ng-if` in the facet validation changes. I did that in combination with other changes and assumed that this change is needed, but it's not needed at all.
Because of `ng-if`, the top-panel element is not part of DOM when we're creating the `resizablePartners` in `table.js` (`resizablePartners` are the elements that should resize while resizing the main element) and therefore it doesn't resize the top-panel at all.
P.S. This is a very simple change. I created this PR to run test cases on Actions before merging it.
=> Fix recordset facet panel resizable behavior

common/modal.js, common/templates/searchPopup.modal.html, test/e2e/specs/delete-prohibited/recordset/misc-facet.spec.js, test/e2e/utils/chaise.page.js
This PR addresses an issue with the facet "Show More" popup not allowing the user to submit a selection of 0 rows when the popup loaded with more than 0 rows. More details can be found in the attached issue.
=> Allow submission of empty set when facet popup loaded with selections made

.github/workflows/e2e.yml, Makefile, docs/dev-docs/e2e-test.md, test/e2e/utils/protractor.parameterize.js
Currently for testing we use a bunch of npm dependencies that are not needed while building chaise. That's why we listed them as part of `devDepencendies` and this allows us to do `npm install --production` during `make install`, while we have to do `npm install` before testing.
I'm not sure when this happened, but it seems like the behavior of `npm install --production` is not the same as before. If you do `npm install` and then `npm install --production` it will remove all the dev dependencies. That's why the test cases in Github Actions started failing since last week.
So,
- Introduced a `deps-test` Makefile target to install dependencies after doing `make install` in Github Actions.
- Updated `test` Makefile targets to not install anything by default and only run tests. Previously we …
=> Change makefile targets to fix Github Actions issues

common/navbar.js, common/table.js, common/utils.js
Changes included remove the preventDefault function call from navbar branding and navbar menu click events.
Other changes included makes sure that saved query properties are initialized before any of the functionality is triggered. Fixed a bug that Karl brought up regarding a request triggering that was failing silently in the background on app-dev.nih-cfde.org.
Related message:
> Mike showed me some app-dev logs which imply to me that something might be wrong with the saved query event logging
> it was a two-column access with RID and last execution time, complaining that RID was null
=> Fix navbar link click events

chaise-config-sample.js, common/styles/scss/_viewer-app.scss, common/utils.js, docs/user-docs/chaise-config-deprecated.md, docs/user-docs/chaise-config.md, viewer/annotations/annotations.controller.js, viewer/annotations/annotations.js, viewer/index.html.in, viewer/viewer.app.js, viewer/viewer.controller.js, viewer/viewer.utils.js
When I added support for dynamic ACLs in chaise apps, I didn't properly do so for the annotation list. This PR will ensure that we're properly showing "edit" and "delete" buttons in the annotation list based on dynamic ACLs.
While testing this I encountered a case where user can "delete" an annotation but cannot "edit" is. The current UI doesn't properly support that since the "delete" button is only available in the "edit form".
issue: #2162
=> Proper dynamic ACL support in viewer app annotation list

.github/workflows/e2e.yml, common/faceting.js, common/inputs.js, common/modal.js, common/recordCreate.js, common/table.js, common/utils.js, docs/user-docs/chaise-config-change-logs.md, docs/user-docs/chaise-config.md, record/record.controller.js, recordedit/form.controller.js, recordset/recordset.app.js, test/e2e/specs/all-features/chaise-config.js, test/e2e/utils/record-helpers.js
This PR adds a chaise config property to allow for control over the initial display of the facet panel in search popups on modal load. The property includes 2 arrays, open and closed, of contexts related to compact and its sub-contexts.
To determine the state of the facet panel, chaise will get the value from ermrestJS which calculates the value based on the context of the reference and the defined `facetPanelDisplay` value.
Other changes include using more specific "contexts" when contextualizing a reference in places in chaise. The only reference that hasn't been changed was the reference used for the `Show More` popup in faceting.
=> Compact select association

common/inputs.js, recordedit/index.html.in, test/e2e/specs/delete-prohibited/recordset/misc-facet.spec.js, test/e2e/utils/chaise.page.js, test/e2e/utils/recordedit-helpers.js
Whether the input value is required or not (based on the `nullok` flag in the model), Chaise allows users to "clear" the input. And the "required" check is only done when users attempt to submit the form.
This was not the case for the color inputs. If a color typed column had `nullok=false`, Chaise wouldn't allow users to clear the input. As a result, the input would show the "black color" on load, while the actual saved value is still `null`. This would lead to a confusing UX, as it is described in [#2061](https://github.com/informatics-isi-edu/chaise/issues/2061). 
So in this PR, I just made sure to allow empty values in the color input and then let Angular handle the "required" check.
=> Handle empty input for colors like any other input

common/modal.js, common/templates/shareCitation.modal.html, test/e2e/data_setup/schema/record/editable-id.json, test/e2e/data_setup/schema/record/product-unordered-related-tables-links.json, test/e2e/specs/all-features-confirmation/record/presentation.spec.js, test/e2e/specs/all-features/record/copy-btn.spec.js, test/e2e/specs/all-features/record/related-table.spec.js, test/e2e/utils/record-helpers.js
In [this ermrestjs commit](https://github.com/informatics-isi-edu/ermrestjs/commit/20e0fa747533ad8f42938ed057eb6c8655ec0fb0), I added a new `Table.supportHistory` API. This PR will make sure chaise is using this API to conditionally add the version link in the share and cite popup.
The main purpose of this PR is to run test cases on Github Actions before merging with master.
related issue: #2002
=> show the versioned link in share popup only if table supports it

viewer/viewer.utils.js
This PR addresses #2124 issue. In terms of code change in this PR, I only modified the `updateChannelConfig` function to send the value of `pseudoColor` sent from osd-viewer alongside the `ChannelConfig`. The rest of the changes can be found in [osd-viewer#96 PR](https://github.com/informatics-isi-edu/openseadragon-viewer/pull/96). I'll explain why we decided to make these changes in the following.
As part of the image processing pipeline, We store a `pseudoColor` with the greyscale images. This value was used in the viewer app to populate the "Hue" control.  When we modified the channel controls to make them persistent in the database, we introduced a `ChannelConfig` JSON column with a `hue` property. And therefore, I modified the code to use this `hue` if `ChannelConfig` is defined (and …
=> Change how pseudoColor is used and stored

.github/workflows/e2e.yml, Makefile, README.md, docs/dev-docs/e2e-test.md, docs/user-docs/installation.md, docs/user-docs/login-app.md, docs/user-docs/navbar-app.md, docs/viewer/viewer-app.md, package.json
After reviewing how the `make install` command works, we realized that it's wrong and should be changed. This command is doing the following two steps:
Build the chaise bundles in the `dist` folder alongside the other chaise folders.
Deploy the built files to the given location (local or remote, depending on how the environment variables are defined).
In a multi-user environment (like the automated build process in our recipes), the first step should be performed by the owner of the folder. And the second step can only be performed by the user that has access to the `/var/www/html/` location. So we shouldn't have assumed that a single user can perform these two actions and should just separate them.
That's why in this PR, I removed the `install` target and introduced a new `deploy` target …
=> Remove makefile install target and introduce deploy

common/faceting.js, test/e2e/specs/delete-prohibited/recordset/histogram-facet.spec.js
This PR changes how the min and max is done for timestamp and float type facets. Both will have an epsilon adjusted value used for the min and max to make sure fractional seconds and floating point precision is handled. Float precision is consistent from user input to display to server request
Opening this PR to run test cases in CI (specifically `histogram-facet.spec.js`).
=> Float and timestamp precision improvements for range picker

src/assets/scss/_faceting.scss, src/components/FacetHeader.tsx, src/components/facet-header.tsx, src/components/faceting.tsx
Changes pushed to panel-header branch are:
Made sure the header looks the same as master (Old Angular).
Made sure the header height and font is the same
Made sure the "chevron" looks the same
Conditionally added the class when the header has a comment (just like the columns in recordset-table.tsx)
Made sure ellipsis should work properly:
-- If the header has comment, always show the comment.
-- Otherwise, if the ellipsis is displayed, the tooltip should show the header name.
=> Faceting > HTML structure > panel header

common/utils.js, test/e2e/specs/all-features/chaise-config.js, test/e2e/specs/all-features/navbar/base-config.spec.js, test/e2e/utils/chaise.page.js
We decided to only enable `mailto` in our list of "sanitized" hrefs in angularJS. After closing this PR, the corresponding issue should remain open until this is implemented in react branch.
Linking issue #2202 here so it isn't automatically closed by attaching it to the "Development" option.
=> mailto links prepended with unsafe

src/components/modals/login-modal.tsx, src/providers/authn.tsx, src/providers/error.tsx
This PR fixes the attached issue when the login dialog is opened because of ermrestJS triggering the attached function from `setHTTP401Handler`. This fixes the login error case in the issue and any others that would trigger the login modal to show because of improper authorization when `ermrestJS` tries to make a request to `ERMrest`.
I'm also calling `hideLoginModal()` in the callback we talked about that should be addressed. I noted in the comments in the code that this function is registered before the modal is opened so I can't make sure the modal is open before closing it. I also can't check to see if this process was triggered some other way (maybe from the error dialog) that doesn't require a reload and falls into this case.
=> Dismiss login modal after logging in from 401 http handler

src/assets/scss/_input-switch.scss, src/components/input-switch.tsx, src/components/input-switch/boolean-field.tsx, src/components/recordedit/form-container.tsx, src/components/recordedit/recordedit.tsx, src/providers/recordedit.tsx, src/utils/input-utils.ts, src/utils/recordedit-utils.ts
This PR will add `boolean-field.tsx` component. While working on this I found several issues. I created this PR mainly to be able to explain those issues so later we can get back to this and fix them.
- Recordedit doesn't behave properly if the column names have white space. It's failing to pick up the value, and in dev mode, as soon as I change the input I'm getting an error that says, `A component is changing an uncontrolled input to be controlled`. This shows that the input wasn't even setup properly.
- Recordedit is not ensuring the required fields are non-empty before sending the request to ermrestjs. As far as I could tell, in `react-hook-form` we should be able to do the following:
```ts
const registerOptions = {
required: columnModel?.isRequired ? ERROR_MESSAGES.REQUIRED : false, …
```
=> React boolean input

src/assets/scss/_facet-choice-picker.scss, src/assets/scss/_recordset.scss, src/assets/scss/_variables.scss, src/assets/scss/app.scss, src/components/faceting/facet-check-list.tsx, src/components/faceting/facet-choice-picker.tsx, src/components/recordset/recordset-table.tsx, src/components/recordset/recordset.tsx, src/components/selected-rows.tsx, src/models/recordset.ts, test/e2e/data_setup/schema/recordset/faceting.json, test/e2e/specs/delete-prohibited/recordset/ind-facet.spec.js, test/e2e/specs/delete-prohibited/recordset/misc-facet.spec.js, test/e2e/utils/chaise.page.js
Currently, we're showing all the selected choices in the facet panel. So if users open the facet panel and select 50 rows, we will show all the selected 50 items in the facet panel. This would make the facet panel very difficult to use as users must scroll a lot to get to the other displayed facets.
This PR will ensure we're limiting the number of selected items we're displaying in the panel. In this case, I'm showing a warning below the list to inform users about the hidden items.
As part of this PR, I also added tooltips to show more/details buttons and ensured all the tooltips/text related to facets were consistent.
=> Limit the number of displayed selected items in facet panel

src/assets/scss/_button-group.scss, src/assets/scss/_inputs.scss, src/assets/scss/_recordedit.scss, src/components/input-switch.tsx, src/components/input-switch/array-field.tsx, src/components/input-switch/boolean-field.tsx, src/components/input-switch/color-field.tsx, src/components/input-switch/foreignkey-field.tsx, src/components/input-switch/json-field.tsx, src/components/input-switch/longtext-field.tsx, src/components/recordedit/form-container.tsx, src/components/recordedit/key-column.tsx, src/components/recordedit/recordedit.tsx, src/models/recordedit.ts, src/providers/recordedit.tsx, src/utils/input-utils.ts, src/utils/recordedit-utils.ts
While implementing dynamic ACLs I realized that the column-based layout for recordedit form is going to make the implementation very difficult. This layout caused a lot of issues related to height management and we had to add several state-variables just to handle heights. 
Most of the changes in this PR is removing the state-variables and height logic that we had. By using row-based, we don't need to worry about the height of the `.form-container` and we just need to make sure `.entity-key-column` has the same height as `.form-contaner`. To do so, I just had to add a `ResizeSensor`.
P.S. I also changed the indentation of `_recordedit.scss`, so you'll notice a lot of changes in that file as well.
=> Change recordedit layout to be row-based and add dynamic ACL support

src/assets/scss/_recordedit.scss, src/components/input-switch/boolean-field.tsx, src/components/input-switch/foreignkey-field.tsx, src/components/recordedit/form-container.tsx, src/components/recordedit/key-column.tsx, src/components/recordedit/recordedit.tsx, src/models/recordedit.ts, src/providers/recordedit.tsx, src/utils/input-utils.ts, src/utils/recordedit-utils.ts
The main change in this PR is adding the select-all functionality.
In the AngularJS version, we're creating an `allInput` prop in `columnModel` that captures the select-all input. Since we're assuming `columnModels` will not change after initialization, I'm initializing the form with one additional input for each column and naming them with  `-1-${colName}` format (essentially, we now have a hidden form with formNumber=-1).
I didn't make any changes to how we're storing datetime values. I have to think more about it because what we have works and doesn't add too much overhead compared to alternatives. 
Also, I Made some changes to the HTML layout to fix scrolling behavior and accommodate the select-all UI. So instead of directly merging my changes, I created the PR to double-check the …
=> Implement select-all functionality

src/components/faceting/facet-range-picker.tsx, src/components/input-switch/date-time-field.tsx, src/components/input-switch/input-switch.tsx, src/components/range-inputs.tsx, src/utils/input-utils.ts
This PR cleans up the implementation for `timestamp` and `timestamptz` inputs and the places they are used. In the case of `facet-range-picker`, the `absMin`/`absMax` values that are stored in the `compState` variable are no longer objects. Instead the string representation of the `timestamp[tz]` values are stored and passed to `rangeInputs` where they are then digested for setting values in the timestamp, date, and time inputs separately.
The validation for `timestamp[tz]` was triggering on form submission since in some cases the values were not formatted in the format that the validation function expected. When a value changes in the `date` or `time` input, in the case of `timestamp[tz]`, the `datetime` value is passed into moment so the appropriate timezone can be appended.
=> timestamp and timestamptz validation

package-lock.json, package.json, src/assets/scss/_input-switch.scss, src/assets/scss/_range-input.scss, src/components/faceting/facet-range-picker.tsx, src/components/input-switch/date-field.tsx, src/components/input-switch/date-time-field.tsx, src/components/input-switch/input-field.tsx, src/components/input-switch/input-switch.tsx, src/components/range-inputs.tsx, src/components/recordedit/form-container.tsx, src/utils/constants.ts, src/utils/input-utils.ts, src/utils/recordedit-utils.ts
When we migrated the recordset app, we used the browser's `date` and `time` inputs for facet range pickers.
But now that we've used this feature more and discussed it, we prefer the old AngularJS method where we used `text` inputs with special masks and validators. The following are some of the issues with `date`/`time` input type:
- The behavior is not consistent between browsers. It also shows different formats based on user locale (e.g., 24hr time vs. 12hr), which could confuse UX.
Partial values were causing issues in both date and time.
- We cannot easily support multiple formats for time.
- We have to test the validation and date/time pickers manually.
Therefore, this will modify date and time inputs into text inputs with special masks and validators (the same as AngularJS) …
=> handle date and time inputs manually

src/utils/recordedit-utils.ts, test/e2e/data_setup/data/editable-id/editable-id-table.json, test/e2e/data_setup/schema/record/editable-id.json, test/e2e/specs/all-features/record/copy-btn.spec.js, test/e2e/utils/recordedit-helpers.js
When users copy a record, we populate the form based on the copied record. Regarding assets, we only copy the hatrac URL, not the extra metadata columns. This PR will make sure we're also copying the metadata columns. 
This is something that I wasn't sure of when I was finalizing the Recordedit React app and left it so I can discuss it with @jrchudy first. 
We can use this branch to add the extra changes to asset implementation if needed.
=> Properly set asset metadata values

common/faceting.js, common/table.js
This PR will resolve the #2295. To do this, I'm using the helper function that I added to ermrestjs. With this, the request will now properly handle url length limitation and also use the `any` syntax if the catalog allows it. I didn't want to add another unnecessary change to ermrestjs yet, so I used the "private" function for now.
To make sure I haven't broken the favorites feature, I [added a test schema to ermest-data-utils](https://github.com/informatics-isi-edu/ErmrestDataUtils/commit/be7a76df075cef0e2d51b476dbff92eefb4b23a2) and tested it that way. But I think before merging we might want to test this on cfde's test server. I don't have access to that server so I cannot test it that way.
=> Properly handle url length limitation in favorites requests

src/components/input-switch/boolean-field.tsx, src/providers/recordedit.tsx, src/utils/input-utils.ts, test/e2e/data_setup/schema/recordedit/product-add.json, test/e2e/specs/all-features-confirmation/recordedit/add.spec.js
We're relying on react-hook-form for the "required" check. But it's doing a "truthy" check which doesn't work well with how we've implemented the `BooleanField`s.  This field is special as we're storing the actual boolean value in the form, and the logic to turn this boolean to the displayed dropdown is hidden inside the field implementation. 
So in this PR, I created a custom `required` validator for this component. 
This wasn't an issue for other inputs like an integer. For those inputs, we're using "text" input, so to react-hook-form, a `0` value is actually `"0"` and therefore "truthy".
Fixes #2303.
=> Properly handle required check for boolean inputs

package.json, src/assets/scss/_modal.scss, src/assets/scss/app.scss, src/components/app-wrapper.tsx, src/components/faceting/faceting.tsx, src/components/modals/profile-modal.tsx, src/components/recordset/recordset.tsx, webpack/app.config.js
This PR will,
- Properly handle the race condition between facet registration and using the registered facet callbacks in the recordset app. Because of this race condition, the recordset modal in the plot app was sometimes throwing a terminal error. I couldn't reproduce this in Chaise though.
- Ensure the URL is not changed in the recordset app when we show errors (useful for the ‍‍‍`UnsupportedFilters` error where users could technically login and retry).
- Properly include `modal.scss` so it also works in deriva-webapps.
- Improve webpack configuration by,
- Breaking large chunks into multiple based on size. Apart from the chunks created for each app, I was creating `common`, `vendor`, `vendor-react`, and `vendor-bootstrap` chunks. But now, webpack will break these named chunks into …
=> Various Improvements

src/components/faceting/facet-range-picker.tsx, src/components/range-inputs.tsx
This PR fixes issue #2306. 
Adding `tickmode: 'linear'` to the `yaxis` communicates to plotly that the values displayed for `yaxis` should be a linear relation. the other bug in this PR was checking the difference between min and max incorrectly by doing a conversation and diff instead of using  the moment API, `isBefore`.
Another bug was found while trying to fix the other bugs, we were allowing users to "zoom" in the plot using the builtin plotly functionality when the plot couldn't be zoomed anymore (providing a confusing UX).
=> Range picker bugs

package-lock.json, src/components/app-wrapper.tsx
I'm currently experimenting with testing deriva-webapps locally and the only issue was the initial session fetch. So in this PR I added a flag to skip this step.
The changes are simple and the PR is for making sure all test cases are passing.
=> Add a flag to AppWrapper to skip initial session fetch

docs/user-docs/integrate-with-google-tag-manager.md
We recently realized that Google Analytics is not reporting URL fragments. So I tried to figure out how to fix that and modified the documentation to include the new information.
As part of this, I had to write a JavaScript script to extract the URL path we care about. That's why instead of directly pushing the code I created this PR so @jrchudy  can review the chagnes.
P.S. I'm not sure if having the code directly in the markdown page is good or bad. GitHub offers a "copy" button so they can just copy and paste. But it's making the document very lengthy.
=> Document how to add chaise urls to GA report

common/utils.js, docs/user-docs/chaise-config-change-logs.md, docs/user-docs/chaise-config-deprecated.md, docs/user-docs/chaise-config.md, src/providers/authn.tsx, src/providers/error.tsx, src/services/config.ts, src/services/log.ts, src/utils/constants.ts, src/utils/uri-utils.ts, test/e2e/specs/all-features-confirmation/chaise-config.js, test/e2e/specs/all-features-confirmation/recordset/presentation.spec.js, test/e2e/utils/recordedit-helpers.js
This PR was initially created to change the behavior of `ermrestLocation`. 
We're using `ermestLocation` to find where ermrest is, so allowing it on the `chaise-config` annotation doesn't make sense. We should only honor it when it's part of `chaise-config.js`. After discussing it, we decided to do the same thing with `defaultCatalog`.
We also didn't like how in `defaultTables` we're supposed to encode the catalog numbers and decided to deprecate it and replace it with `defaultTable`. It's more or less the same property. The only difference is that now the catalog number is implied. 
Summary of code changes:
- Added a concept of `CHAISE_CONFIG_STATIC_PROPERTIES` properties. These properties will only be allowed on the `chaise-config.js` file (`ermestLocation` and `defaultCatalog`). 
- …
=> Change behavior of some chaise-config properties (ermrestLocation, defaultCatalog, defaultTables)

docs/user-docs/navbar-app.md, src/assets/scss/app.scss, src/components/app-wrapper.tsx, src/libs/login.tsx, src/libs/navbar.tsx, src/services/config.ts, src/utils/ui-utils.ts, webpack/app.config.js
This PR will improve the Navbar UX in static sites by applying most of the changes I described [here](https://github.com/informatics-isi-edu/chaise/issues/1978#issuecomment-1613632197). The changes are:
- Ensure navbar dependencies are not using `defer` and, therefore, have priority over the static content. 
- Show a spinner while waiting for the session and catalog if the navbar has some preserved space.
=> Improve Navbar UX in static sites

src/assets/scss/_record.scss, src/components/record/related-table-actions.tsx, src/components/record/related-table-header.tsx, src/components/recordedit/resultset-table-header.tsx, test/e2e/specs/all-features/record/related-table.spec.js, test/e2e/utils/chaise.page.js, test/e2e/utils/record-helpers.js
This PR focuses on making the related main section and table section buttons responsive based on available space. 
Other changes:
- Add a Bulk edit button to related entities.
- Change the icon of "custom mode"
=> Make related table actions responsive

.github/workflows/e2e.yml, docs/dev-docs/dev-guide.md, src/components/alerts.tsx, src/components/clear-input-btn.tsx, src/components/display-value.tsx, src/components/input-switch/longtext-field.tsx, src/components/modals/markdown-preview-modal.tsx, src/components/navbar/banner.tsx, src/components/navbar/login.tsx, src/components/navbar/navbar-dropdown.tsx, src/components/navbar/navbar.tsx, src/components/spinner.tsx, src/components/split-view.tsx, src/components/title.tsx, src/components/tooltip.tsx, src/utils/menu-utils.ts, src/utils/ui-utils.ts, test/e2e/specs/all-features-confirmation/recordedit/add.spec.js, test/e2e/specs/all-features-confirmation/recordedit/edit.spec.js, test/e2e/specs/all-features/record/copy-btn.spec.js, test/e2e/specs/default-config/recordedit/multi-col-types.spec.js, test/e2e/specs/default-config/recordedit/multi-edit.spec.js
This RP will modify the `DisplayValue` component to handle chaise tooltips. Since we have to do this in JavaScript and outside of React, I'm [directly using bootstrap's tooltips](https://getbootstrap.com/docs/5.3/components/tooltips/#enable-tooltips) for this.
=> Support chaise tooltips

src/assets/scss/_button-group.scss, src/assets/scss/_buttons.scss, src/assets/scss/_record.scss, src/assets/scss/_recordset-table.scss, src/assets/scss/app.scss, src/assets/scss/helpers.scss, src/components/recordset/table-row.tsx
This PR will address [the issue](https://github.com/informatics-isi-edu/chaise/issues/2349)
Summary of changes:
The aim of this PR change is to fix the inconsistency in button spacing issue.
With this PR we have center aligned the buttons using display: 'inline-flex'.
Also for view details action button a height is given and padding is removed to fix the alignment
The deployed version is [here](https://dev.gudmap.org/~povijaya/chaise/record/#2/Common:Collection/RID=14-4KG6)
=> Fixing spacing around chaise buttons

src/components/modals/share-cite-modal.tsx, src/components/recordset/recordset.tsx, src/components/share-cite-button.tsx, src/components/tooltip.tsx, src/utils/message-map.ts, src/utils/ui-utils.ts, test/e2e/specs/all-features-confirmation/recordset/presentation.spec.js
This PR,
- Refactores the `copyToClipboard` function to return a promise.
- Changes the share and cite popup links to use the same function. We were only using the deprecated API for copy in this case (which wasn't working properly on some browsers).
- Dynamically changes the tooltip to say "Copied!" so users are aware of the action.
- Adds a new property to `ChaiseTooltip` component to remount the tooltip if its content has changed. Without this change the tooltip arrowhead position would stay in the same place. As a result the tooltip would go outside the window in some cases.
=> Improvements to copy to clipboard feature

webpack/app.config.js
We recently realized that bootstrap rules are overwriting chaise rules in deriva-webapps. Upon looking at it, I realized that the chaise CSS files were added before the bootstrap ones. 
I always assumed that webpack is going to add CSS files based on the `import` statements that we have. But it seems like the `priority` we've set for the `cacheGroups` is dictating the order. Based on webpack's documentation, the `priority` is to ensure which rules should be prioritized when a given `test` matches multiple. That's why I had the default `node_modules` as the lowest priority.
So, to fix this, I rearranged the priorities and ensured the default `vendor-rest` excludes other rules. This way, the `priority` is just for dictating the order of added asset files and not tie-breaking the rules. …
=> Change order of assets in webpack config

src/components/recordset/table-row.tsx
since sensors are delayed, they may see an empty row. Before this was triggering the overflow logic when the rows would dissapear so the reference to rowConainter.current would still be present. Now that it's delayed, current is updated (next state update cycle) and should be checked before trying to iterate.
=> Bug in resize sensor logic for table row

src/assets/scss/_record-main-section.scss, src/assets/scss/_recordset.scss, src/assets/scss/_variables.scss, src/assets/scss/app.scss, src/assets/scss/maps/_record-page-spacing.scss, src/components/record/record-main-section.tsx, src/components/recordset/recordset.tsx, src/providers/recordset.tsx
This PR includes two issues I noticed while doing regression testing on atlas-d2k. The changes are,
- While changing the page limit, the page will get stuck if users pick the already selected page limit. I'm now triggering the update properly.
- The recordset spinner was displayed in the middle of the page while only showing whether the main table data has been loaded. It's now sticky inside the `main-body`, similar to how the record page's main section spinner works.
=> Small fixes related to recordset app

src/components/modals/share-cite-modal.tsx, src/utils/string-utils.ts, test/e2e/data_setup/schema/record/product.json, test/e2e/data_setup/schema/recordset/saved-query.json, test/e2e/specs/all-features-confirmation/record/presentation.spec.js, test/e2e/specs/all-features/recordset/saved-query.spec.js
This PR will add a `.` after the `author_pattern` and `title_pattern` in the citation shown in the share and cite popup.
Modified an existing test case to verify the `.` is added properly. I used an existing `citation` annotation for the saved_query tests to test the case with a `.` defined in both `author_pattern` and `title_pattern` (the `.` part of `lgt` column used in the `title_pattern`). I don't think this `citation` annotation was used before this so I figured I would use it for this test case.
Relevant issue #1853 
When this is merged, I will update [annotation.md](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/user-docs/annotation.md#tag-2018-citation) in ermrestJS.
=> Add `.` in citation in share and cite popup

src/utils/head-injector.ts, src/utils/uri-utils.ts, test/e2e/specs/all-features-confirmation/recordset/presentation.spec.js
As the title suggests, this PR will make sure we're properly using the `defaulTable` when users navigate to pages like `/chaise/recordset/#1`. The actual change in this PR is fixing the implementation of `getCatalogId` so that it does not rely on the `chaiseURItoErmrestURI` and finds the ID by itself.
Assume we don't have any `defaultCatalog` defined on `chaise-config.js` and that the following catalog annotation is used on catalog with id `1`:
```
"tag:isrd.isi.edu,2019:chaise-config": {
"defaultTable": {
"schema": "isa",
"table": "dataset"
}
}
```
If users navigate to the `/chaise/recordset/#1` location, we expect chaise to use the default table. Instead, they would see an error saying that the default table is not defined.
This is because in `ConfigService.configure` we call …
=> Make sure defaultTable chaise-config is properly supported

src/libs/login.tsx, src/libs/navbar.tsx, src/pages/help.tsx, src/pages/login.tsx, src/services/config.ts, src/utils/uri-utils.ts
As part of our `config` service, we parse the URL to find the catalog id. This is done so we can use the `chaise-config` annotation that might be defined on the catalog.
However, static sites might not follow the same URL pattern as chaise and use hash for other reasons. Because of this, going to a static page like https://staging.atlas-d2k.org/gudmap/citing-gudmap/#creating-citable-data-collections would result in an error because we're assuming `creating-citable-data-collections` is the catalog id. 
So, in this PR, I added a new boolean to skip this logic for the navbar and login libs. I also used this for the help and login apps since they're not following the same URL pattern either.
P.S. The changes are simple and I created this PR mostly to announce and run CI tests. I'll merge it …
=> Avoid parsing url to find the catalog id on static sites

src/components/modals/iframe-field-modal.tsx, test/e2e/data_setup/schema/recordedit/input-iframe.json, test/e2e/specs/all-features/recordedit/input-iframe.spec.ts, test/e2e/utils/input-iframe-test.html
Prior to merging #2340, array values were stored as strings in react-hook-form. So the `iframe-field-modal.tsx` code wasn't doing anything special for the arrays and `populateSubmissionRow` would eventually turn this string into a proper array.
However, with the new implementation, we expect array values to follow a specific pattern, and this PR will make sure this component also stores array values properly.
Because of this bug, after users select a value using the iframe, as soon as the `populateSubmissionRow` was called (due to opening a foreign key popup or clicking on submit), they would see a terminal error with the following message
```
l.map is not a function
```
P.S. I also changed the test case to have an array column, so we can test this scenario.
=> Properly handle array inputs in iframe-field-modal

src/components/faceting/facet-range-picker.tsx, test/e2e/specs/delete-prohibited/recordset/individual-facet.spec.ts
This PR will add null option to range facets (#2364).
=> Add null option to range facets

.eslintrc.js, Makefile, test/e2e/setup/playwright.model.ts, test/e2e/setup/playwright.setup.ts, test/e2e/specs/delete-prohibited/chaise-config.js, test/e2e/specs/delete-prohibited/navbar/playwright.config.ts, test/e2e/specs/delete-prohibited/playwright.config.ts
A while ago, I modified the catalog creation step of our test framework to add aliases to the created catalog. This allowed us to test the `defaultCatalog` property since we could hardcode the alias inside the `chaise-config.js` files.
This worked properly while I was testing it on my own. However, since then, we have found that the alias creation has limitations when multiple users use the same alias or if multiple users want to run test cases simultaneously.
So this PR will remove the alias creation step and instead will inject a line into the `chaise-config.js` like the following:
```
chaiseConfig.defaultCatalog = 'id_of_the_newly_created_catalog';
```
Since we don't need this for all the test cases, I added a new `addDefaultCatalogToChaiseConfig` to our test options.
The following are …
=> Inject defaultCatalog property to chaise-config and remove catalog alias creation step

src/components/faceting/faceting.tsx
Currently the facet order is stored as soon as you open a recordset page. As we mentioned in [here](https://github.com/informatics-isi-edu/chaise/issues/2528#issuecomment-2357319732) this can cause issues. So in this PR I added a flag to ensure we're updating the order only if the user made any changes to the page.
=> Only save facet order in local storage if the user initiated it

.github/workflows/e2e.yml, test/e2e/data_setup/data/product/association_table_w_three_fks.json, test/e2e/data_setup/data/product/leaf_table_for_three_fks.json, test/e2e/data_setup/data/product/third_table_for_three_fks.json, test/e2e/data_setup/schema/record/product-unordered-related-tables-links.json, test/e2e/specs/all-features/record/related-table.spec.ts
This PR adds a test case to make sure defining the annotation will still properly trigger the bulk create foreign key UI in recordedit app with a prefill value.
These changes should be merged with [this PR](https://github.com/informatics-isi-edu/ermrestjs/pull/1018) in ermrestJS.
=> End-to-end test for "bulk_create_foreign_key" annotation property

src/assets/scss/_recordedit.scss, src/components/recordedit/form-row.tsx, src/components/recordedit/multi-form-input-row.tsx
This PR changes how the styles for the key column are defined in recordedit so that the key column will be taller than the form inputs when the column displayname text is long. 
I'm using `height` to adjust the height for the key column. The entity value has a similar adjustment made when the header is taller and the height can't go below a certain threshold.
About the key column CSS changes:
- removed `height: 47px` from stylesheet
- the height is "unset" each time we calculate the height of the header compared to the inputs. This allows the bounding rect height to be more precise
- we don't want to rely on `header.style.height` since that's the property we are setting ourselves (or unsetting)
-  relies on `min-height` and content of the header to change the height when the key column …
=> Recordedit column headers text overflow

src/pages/login.tsx, src/providers/authn.tsx, src/providers/recordedit.tsx
If you use the organization login feature of globus, the login popup gets stuck and never closes. So, users had to manually close the popup and refresh the main page.
After investigating this, I realized that the `window.opener` API becomes `null` in this scenario. So, in this PR, I completely rewrote this logic to use the `BroadcastChannel` API instead.
With `BroadcastChannel`, we can broadcast this event to all chaise pages. But since the goal of this PR is fixing the bug (and not changing the expected behavior), I'm only broadcasting to the page that calls the login flow. We should have a discussion if we want to change this behavior.
=> Fix the login issue regarding globus organization login flow
